export const C = {
  bg: "#0B0F19",
  card: "#151C2C",
  cardLight: "#1E293B",
  border: "#334155",
  teal: "#145952",
  tealDark: "#0C3F3A",
  tealGlow: "#14595225",
  amber: "#C2952A",
  amberGlow: "#C2952A25",
  text: "#F8FAFC",
  muted: "#94A3B8",
  danger: "#EF4444",
  green: "#145952",
  greenDark: "#0C3F3A",
  purple: "#8B5CF6",
};

export const T = {
  landing: {
    badge: { ar: "✦ أفضل متخصصي التغذية في الشرق الأوسط — بين يديك", en: "✦ Top Nutrition Specialists in the Middle East — At Your Fingertips" },
    heading1: { ar: "خبرة حقيقية في التغذية", en: "Real Nutrition Expertise" },
    heading2: { ar: "مدعومة بأحدث تقنيات الذكاء الاصطناعي", en: "Powered by Advanced AI Technology" },
    desc: { ar: "متخصصو تغذية معتمدون بخبرة تمتد لسنوات، يستخدمون الذكاء الاصطناعي لبناء خطتك الغذائية بدقة لا مثيل لها.", en: "Certified nutrition specialists with years of experience use AI to build your personalized nutrition plan with unmatched precision." },
    warning: { ar: "⚠️ ملاحظة مهمة: بيانات صحتك وأمراضك وأدويتك ضرورية لضمان سلامة خطتك.", en: "⚠️ Important: Your health data, conditions, and medications are essential to ensure your plan's safety." },
    cta: { ar: "ابدأ الاستبيان المجاني ←", en: "Start Free Questionnaire →" },
    time: { ar: "3 دقائق فقط · بدون تسجيل · بدون دفع مسبق", en: "Just 3 minutes · No registration · No upfront payment" },
    staff: { ar: "دخول الموظفين", en: "Staff Login" },
    aiPowered: { ar: "مدعوم بالذكاء الاصطناعي", en: "AI-Powered" },
    features: [
      { icon: "🏅", title: { ar: "متخصصون معتمدون", en: "Certified Specialists" }, desc: { ar: "متخصصو تغذية بخبرة سنوات في الشرق الأوسط", en: "Nutrition specialists with years of experience in the Middle East" } },
      { icon: "🤖", title: { ar: "مدعومون بالذكاء الاصطناعي", en: "AI-Powered" }, desc: { ar: "تقنية متقدمة لخطة دقيقة لجسمك وبلدك", en: "Advanced tech for a precise plan for your body and country" } },
      { icon: "💳", title: { ar: "الدفع على النتيجة", en: "Pay for Results" }, desc: { ar: "تدفع أسبوعياً فقط عند تحقيق تقدم", en: "Pay weekly only when you see progress" } },
      { icon: "🔄", title: { ar: "متابعة أسبوعية", en: "Weekly Follow-up" }, desc: { ar: "متخصصك يعدل خطتك كل أسبوع", en: "Your specialist adjusts your plan every week" } }
    ],
    steps: { ar: "آلية عمل النظام", en: "How It Works" },
    stepsList: [
      { title: { ar: "أجب على استبيان شامل", en: "Complete a Comprehensive Questionnaire" }, desc: { ar: "3 دقائق تغطي صحتك وعاداتك", en: "3 minutes covering your health and habits" } },
      { title: { ar: "الذكاء الاصطناعي يبني مسوّدة خطتك", en: "AI Builds Your Plan Draft" }, desc: { ar: "وجبات مخصصة لجسمك وبلدك في ثوانٍ", en: "Meals tailored to your body and country in seconds" } },
      { title: { ar: "متخصصنا يراجع ويوافق", en: "Our Specialist Reviews & Approves" }, desc: { ar: "خبرة بشرية تراجع كل تفصيلة", en: "Human expertise reviews every detail" } },
      { title: { ar: "متابعة أسبوعية وتعديل مستمر", en: "Real Weekly Follow-up & Continuous Adjustment" }, desc: { ar: "كل أسبوع تُرسل نتائجك، ومتخصصك يعدّل خطتك", en: "Each week you send your results, your specialist adjusts your plan" } }
    ]
  },
  login: {
    title: { ar: "دخول الموظفين", en: "Staff Login" },
    hint: { ar: "أدخل رمز الدخول الخاص بك. (admin123 للمدير، spec123 للمتخصص)", en: "Enter your access code. (admin123 for admin, spec123 for specialist)" },
    loginBtn: { ar: "تسجيل الدخول", en: "Login" },
    back: { ar: "العودة كعميل", en: "Back as Customer" },
    error: { ar: "رمز الدخول غير صحيح!", en: "Invalid access code!" }
  },
  quiz: {
    question: { ar: "السؤال", en: "Question" },
    of: { ar: "من", en: "of" },
    optional: { ar: "اختياري", en: "Optional" },
    back: { ar: "← رجوع", en: "← Back" },
    next: { ar: "التالي ←", en: "Next →" },
    generate: { ar: "🚀 أنشئ خطتي بالذكاء الاصطناعي", en: "🚀 Generate My AI Plan" },
    phoneHint: { ar: "يرجى إدخال رقم هاتف صحيح", en: "Please enter a valid phone number" },
    multiHint: { ar: "يمكنك اختيار أكثر من إجابة", en: "You can select multiple answers" },
    healthNoteTitle: { ar: "📝 تفاصيل إضافية عن وضعك الصحي", en: "📝 Additional Health Details" },
    healthNoteSent: { ar: "✓ ستُرسل هذه المعلومات إلى المتخصص مباشرة", en: "✓ This information will be sent directly to the specialist" },
    healthyWeight: { ar: "الوزن الصحي المثالي حسب طولك", en: "Healthy Ideal Weight for Your Height" },
    healthyRange: { ar: "النطاق الصحي", en: "Healthy Range" },
    customTarget: { ar: "أختار هدفي بنفسي", en: "Choose My Own Goal" },
    currentStatus: { ar: "وضعك الحالي", en: "Your Current Status" },
    bmi: { ar: "مؤشر كتلة الجسم", en: "Body Mass Index" },
    popularCountries: { ar: "الأكثر شيوعاً", en: "Most Popular" },
    noResults: { ar: "لا توجد نتائج — جرّب كتابة مختلفة", en: "No results — Try a different search" }
  },
  generating: {
    title: { ar: "متخصصنا يبني خطتك...", en: "Our Specialist is Building Your Plan..." },
    time: { ar: "يستغرق عادةً من 15 إلى 30 ثانية", en: "Usually takes 15 to 30 seconds" }
  },
  error: {
    rateLimit: { ar: "الخدمة مشغولة مؤقتاً", en: "Service Temporarily Busy" },
    rateLimitDesc: { ar: "وصلنا للحد الأقصى للاستخدام. انتظر بضع دقائق وحاول مجدداً.", en: "Usage limit reached. Wait a few minutes and try again." },
    general: { ar: "تعذّر توليد الخطة", en: "Failed to Generate Plan" },
    generalDesc: { ar: "حدث خطأ أثناء التوليد. تحقق من اتصالك بالإنترنت وحاول مجدداً.", en: "An error occurred during generation. Check your internet connection and try again." },
    details: { ar: "تفاصيل الخطأ", en: "Error Details" },
    retry: { ar: "حاول مجدداً ←", en: "Try Again →" },
    restart: { ar: "البداية من جديد", en: "Start Over" }
  },
  plan: {
    pending: { ar: "⏳ بانتظار موافقة المتخصص", en: "⏳ Awaiting Specialist Approval" },
    ready: { ar: "✦ خطتك جاهزة وقيد المراجعة", en: "✦ Your Plan is Ready and Under Review" },
    hello: { ar: "مرحباً", en: "Hello" },
    contact: { ar: "سيتواصل معك المتخصص قريباً", en: "Specialist will contact you soon" },
    level: { ar: "المستوى", en: "Level" },
    points: { ar: "نقطة (XP)", en: "Points (XP)" },
    streak: { ar: "شعلة الالتزام", en: "Commitment Streak" },
    calories: { ar: "سعرة / يوم", en: "cal/day" },
    goal: { ar: "الهدف المقرر", en: "Target Goal" },
    protein: { ar: "بروتين", en: "Protein" },
    carbs: { ar: "كربوهيدرات", en: "Carbs" },
    fats: { ar: "دهون", en: "Fats" },
    weeklyPlan: { ar: "📅 الخطة الأسبوعية", en: "📅 Weekly Plan" },
    preview: { ar: "— معاينة مجانية ليوم واحد 🔒", en: "— Free Preview for One Day 🔒" },
    breakfast: { ar: "🌅 الفطور", en: "🌅 Breakfast" },
    lunch: { ar: "☀️ الغداء", en: "☀️ Lunch" },
    dinner: { ar: "🌙 العشاء", en: "🌙 Dinner" },
    snack: { ar: "🍎 وجبة خفيفة", en: "🍎 Snack" },
    chooseOne: { ar: "اختر بديلاً واحداً فقط لكل وجبة", en: "Choose only one alternative per meal" },
    or: { ar: "أو", en: "Or" },
    locked: { ar: "🔒 باقي المحتوى مقفول", en: "🔒 Remaining content locked" },
    lockedDesc: { ar: "ادفع الآن لفتح جميع الوجبات، التمارين المفصلة، والنصائح الكاملة.", en: "Pay now to unlock all meals, detailed workouts, and full tips." },
    workout: { ar: "🏋️ روتين رياضي منزلي", en: "🏋️ Home Workout Routine" },
    tips: { ar: "💡 نصائح مخصصة لك", en: "💡 Personalized Tips" },
    payment: { ar: "💳 إتمام الاشتراك", en: "💳 Complete Subscription" },
    paymentDesc: { ar: "خطتك جاهزة وتمت مراجعتها. جرّب الأسبوع الأول — إن أحسست بفرق حقيقي، استمر.", en: "Your plan is ready and reviewed. Try the first week — if you feel a real difference, continue." },
    weekFee: { ar: "رسوم الأسبوع", en: "Week Fee" },
    payWeekly: { ar: "يُدفع أسبوعاً بعد أسبوع فقط", en: "Paid weekly only" },
    paid: { ar: "✅ تم الدفع بنجاح — تم تفعيل الخطة كاملة!", en: "✅ Payment Successful — Full Plan Activated!" },
    receipt: { ar: "رقم الإيصال", en: "Receipt Number" },
    sending: { ar: "جاري إرسال الخطة الأسبوعية عبر واتساب...", en: "Sending weekly plan via WhatsApp..." },
    sent: { ar: "📱 تم إرسال الخطة بنجاح إلى رقمك!", en: "📱 Plan sent successfully to your number!" },
    payBtn: { ar: "ادفع الآن عبر PayPal", en: "Pay Now via PayPal" },
    paying: { ar: "جارٍ تأكيد الدفع...", en: "Confirming payment..." },
    secure: { ar: "🔒 دفع آمن عبر PayPal · لا تُحفظ بيانات بطاقتك", en: "🔒 Secure PayPal payment · Your card details are not stored" },
    specialistPanel: { ar: "⚕️ لوحة المتخصص", en: "⚕️ Specialist Panel" },
    admin: { ar: "(مدير)", en: "(Admin)" },
    medicalNotes: { ar: "📝 ملاحظات طبية — للمتخصص فقط", en: "📝 Medical Notes — For Specialist Only" },
    patientNotes: { ar: "📝 ملاحظات المريض بكلامه", en: "📝 Patient Notes in Their Own Words" },
    approve: { ar: "✅ اعتماد الخطة والموافقة عليها", en: "✅ Approve and Confirm Plan" },
    approved: { ar: "✓ تمت الموافقة على الخطة", en: "✓ Plan Approved" },
    backend: { ar: "🔄 تتبع النظام الآلي (Backend Status)", en: "🔄 Backend Status Tracking" },
    paymentStatus: { ar: "حالة الدفع", en: "Payment Status" },
    paidStatus: { ar: "تم الدفع بنجاح", en: "Payment Successful" },
    waitingPayment: { ar: "بانتظار الدفع...", en: "Awaiting Payment..." },
    whatsappStatus: { ar: "إرسال واتساب", en: "WhatsApp Sending" },
    whatsappSentStatus: { ar: "تم الإرسال آلياً عبر Cloud API", en: "Sent automatically via Cloud API" },
    dailyFollowup: { ar: "🔔 متابعة يومية (واتساب - يدوية مؤقتاً)", en: "🔔 Daily Follow-up (WhatsApp - Manual for now)" },
    followupNote: { ar: "سيتم ربطها آلياً عبر Firebase Functions لاحقاً", en: "Will be automated via Firebase Functions later" },
    morningMsg: { ar: "🌅 رسالة الصباح الترحيبية", en: "🌅 Morning Welcome Message" },
    middayMsg: { ar: "☀️ متابعة منتصف اليوم", en: "☀️ Midday Follow-up" },
    eveningMsg: { ar: "🌙 رسالة المساء التحفيزية", en: "🌙 Evening Motivational Message" },
    followupWeek: { ar: "📅 هل مرّ أسبوع على البرنامج؟", en: "📅 Has a Week Passed?" },
    followupDesc: { ar: "أرسل لي نتائجك وسأعدّل خطتك للأسبوع القادم بناءً على تقدمك الفعلي", en: "Send me your results and I'll adjust your plan for next week based on your actual progress" },
    followupBtn: { ar: "متابعة الأسبوع", en: "Follow-up Week" },
    restart: { ar: "← البداية من جديد", en: "← Start Over" },
    your_info: { ar: "📋 معلوماتك", en: "📋 Your Info" },
    age: { ar: "العمر", en: "Age" },
    gender: { ar: "الجنس", en: "Gender" },
    height: { ar: "الطول", en: "Height" },
    weight: { ar: "الوزن", en: "Weight" },
    target: { ar: "الهدف", en: "Target" },
    bmi: { ar: "مؤشر كتلة الجسم", en: "BMI" },
    conditions: { ar: "حالات صحية", en: "Conditions" },
    allergies: { ar: "حساسيات", en: "Allergies" },
    activity: { ar: "نشاط بدني", en: "Activity" },
    food_pref: { ar: "تفضيلات طعام", en: "Food Preferences" },
    country: { ar: "البلد", en: "Country" }
  },
  followup: {
    title: { ar: "متابعة الأسبوع", en: "Week Follow-up" },
    questions: [
      { id: "new_weight", icon: "⚖️", title: { ar: "كم وزنك اليوم؟", en: "What's your weight today?" }, sub: { ar: "قِسه الآن قبل الإجابة للدقة", en: "Measure it now before answering for accuracy" }, type: "number", unit: { ar: "كجم", en: "kg" }, required: true },
      { id: "adherence", icon: "📋", title: { ar: "كم يوماً التزمت بالخطة الغذائية؟", en: "How many days did you stick to the plan?" }, sub: { ar: "كن صادقاً — هذا يساعدني في تعديل خطتك", en: "Be honest — this helps me adjust your plan" }, type: "choice", options: { ar: ["7 أيام كاملة 🏆", "5 إلى 6 أيام ✅", "3 إلى 4 أيام 😐", "يوم أو يومان 😕", "لم أستطع الالتزام 😞"], en: ["7 Full Days 🏆", "5-6 Days ✅", "3-4 Days 😐", "1-2 Days 😕", "Couldn't Commit 😞"] }, required: true },
      { id: "hard_meals", icon: "🍽️", title: { ar: "أي وجبة كانت الأصعب في التطبيق؟", en: "Which meal was hardest to follow?" }, sub: { ar: "سأغيّرها لك في الأسبوع القادم", en: "I'll change it for you next week" }, type: "choice", options: { ar: ["الفطور", "الغداء", "العشاء", "الوجبة الخفيفة", "لم تكن هناك صعوبة"], en: ["Breakfast", "Lunch", "Dinner", "Snack", "No Difficulty"] }, required: true },
      { id: "energy", icon: "⚡", title: { ar: "كيف كان مستوى طاقتك خلال الأسبوع؟", en: "How was your energy level this week?" }, sub: { ar: "الطاقة المنخفضة تعني أن السعرات تحتاج تعديلاً", en: "Low energy means calories need adjustment" }, type: "choice", options: { ar: ["ممتاز — نشيط طوال الوقت 💪", "جيد — بشكل عام مقبول 😊", "متذبذب — أحياناً تعب 😐", "منخفض — تعبت كثيراً 😔", "منهك جداً 🔴"], en: ["Excellent — Energetic All Day 💪", "Good — Generally Okay 😊", "Fluctuating — Sometimes Tired 😐", "Low — Very Tired 😔", "Exhausted 🔴"] }, required: true },
      { id: "side_effects", icon: "🩺", title: { ar: "هل لاحظت أي أعراض جسدية هذا الأسبوع؟", en: "Did you notice any physical symptoms this week?" }, sub: { ar: "أي شيء غير معتاد يهمني أن أعرفه", en: "Anything unusual, I need to know" }, type: "multichoice", options: { ar: ["لا شيء — كل شيء طبيعي ✅", "صداع متكرر", "دوخة أو إغماء", "إمساك أو اضطراب هضمي", "نوم مضطرب", "جوع شديد", "آخر"], en: ["Nothing — All Normal ✅", "Frequent Headaches", "Dizziness or Fainting", "Constipation or Digestive Issues", "Disturbed Sleep", "Extreme Hunger", "Other"] }, required: true },
      { id: "notes", icon: "💬", title: { ar: "هل ثمة شيء تريد إخباري به؟", en: "Is there anything you want to tell me?" }, sub: { ar: "أي ملاحظة أو تغيير في حياتك أو صحتك هذا الأسبوع", en: "Any notes or changes in your life or health this week" }, type: "textarea", required: false }
    ],
    progress: { ar: "السؤال", en: "Question" },
    generateBtn: { ar: "🚀 أنشئ خطة الأسبوع الجديد", en: "🚀 Generate New Week Plan" }
  },
  community: {
    title: { ar: "🌍 المجتمع", en: "🌍 Community" },
    leaderboard: { ar: "🏆 المتصدرون", en: "🏆 Leaderboard" },
    follow: { ar: "متابعة", en: "Follow" },
    unfollow: { ar: "إلغاء المتابعة", en: "Unfollow" },
    posts: { ar: "📸 منشورات التحول", en: "📸 Transformations" },
    postPlaceholder: { ar: "اكتب تعليقاً عن تقدمك...", en: "Write a comment about your progress..." },
    uploadPhoto: { ar: "📷 أضف صورة", en: "📷 Add Photo" },
    publish: { ar: "نشر", en: "Publish" },
    beforeAfter: { ar: "قبل / بعد", en: "Before / After" }
  },
  profile: {
    title: { ar: "الملف الشخصي", en: "Profile" },
    xp: { ar: "نقاط الخبرة", en: "XP" },
    streak: { ar: "الشعلة", en: "Streak" },
    level: { ar: "المستوى", en: "Level" },
    badges: { ar: "شارات", en: "Badges" }
  },
  questions: [
    { id: "first_name", type: "text", label: { ar: "اسمك الأول؟", en: "Your first name?" }, placeholder: { ar: "أدخل اسمك", en: "Enter your name" }, icon: "👤", required: true },
    { id: "phone", type: "tel", label: { ar: "رقم هاتفك (اختياري)", en: "Phone number (optional)" }, placeholder: { ar: "مثال: 0096599001234", en: "Example: 0096599001234" }, icon: "📱", required: false, hint: { ar: "لن نزعجك، فقط للمتابعة الأسبوعية", en: "We'll only use it for weekly follow-up" } },
    { id: "age", type: "number", label: { ar: "كم عمرك؟", en: "How old are you?" }, placeholder: { ar: "مثال: 30", en: "Example: 30" }, unit: { ar: "سنة", en: "years" }, icon: "🎂", required: true },
    { id: "gender", type: "choice", label: { ar: "الجنس", en: "Gender" }, options: { ar: ["ذكر", "أنثى"], en: ["Male", "Female"] }, icon: "⚧", required: true },
    { id: "height", type: "number", label: { ar: "طولك (سم)", en: "Your height (cm)" }, placeholder: { ar: "مثال: 170", en: "Example: 170" }, unit: { ar: "سم", en: "cm" }, icon: "📏", required: true },
    { id: "current_weight", type: "number", label: { ar: "وزنك الحالي (كجم)", en: "Current weight (kg)" }, placeholder: { ar: "مثال: 90", en: "Example: 90" }, unit: { ar: "كجم", en: "kg" }, icon: "⚖️", required: true },
    { id: "target_weight", type: "smart_target", label: { ar: "الوزن المستهدف", en: "Target weight" }, icon: "🎯", required: true },
    {
      id: "health_conditions", type: "multichoice_notes",
      label: { ar: "أمراض مزمنة أو أدوية؟", en: "Chronic diseases or medications?" },
      options: { ar: ["لا يوجد", "سكري", "ضغط", "قلب", "غدة", "كلى", "كبد", "أخرى"], en: ["None", "Diabetes", "Hypertension", "Heart", "Thyroid", "Kidney", "Liver", "Other"] },
      icon: "🏥", required: true,
      warn: { ar: "هذه المعلومات ضرورية لسلامتك", en: "This info is essential for your safety" },
      notePlaceholder: { ar: "اكتب الأمراض والأدوية بالتفصيل...", en: "List any diseases & medications..." }
    },
    {
      id: "allergies", type: "multichoice_notes",
      label: { ar: "حساسية أو أطعمة ممنوعة؟", en: "Allergies / forbidden foods?" },
      options: { ar: ["لا يوجد", "لاكتوز", "جلوتين", "مكسرات", "بيض", "بحريات", "أخرى"], en: ["None", "Lactose", "Gluten", "Nuts", "Eggs", "Seafood", "Other"] },
      icon: "⚠️",
      notePlaceholder: { ar: "أي أطعمة لا تتحملها؟", en: "Any foods you can't eat?" }
    },
    {
      id: "activity", type: "choice",
      label: { ar: "مستوى نشاطك البدني", en: "Physical activity level" },
      options: { ar: ["لا أمارس رياضة", "خفيف (مرة بالأسبوع)", "متوسط (3 مرات)", "عالي (يوميًا)"], en: ["Sedentary (no exercise)", "Light (1x/week)", "Moderate (3x/week)", "Active (daily)"] },
      icon: "🏃"
    },
    {
      id: "food_pref", type: "multichoice",
      label: { ar: "تفضيلاتك الغذائية", en: "Your food preferences" },
      options: { ar: ["آكل كل شيء", "نباتي", "دجاج وسمك فقط", "لحوم حمراء", "لا أحب الخضروات"], en: ["Eat everything", "Vegetarian", "Chicken & Fish only", "Red meat", "Don't like vegetables"] },
      icon: "🥗"
    },
    { id: "country", type: "country_search", label: { ar: "دولة إقامتك", en: "Your country" }, placeholder: { ar: "ابحث عن دولتك...", en: "Search your country..." }, icon: "🌍", required: true },
  ],
  common: {
    loading: { ar: "جارٍ تحليل بياناتك...", en: "Analyzing your data..." },
    loading2: { ar: "متخصصنا يدرس ملفك الصحي...", en: "Our specialist is reviewing your health file..." },
    loading3: { ar: "تخصيص الوجبات حسب جسمك وبلدك...", en: "Customizing meals for your body and country..." },
    loading4: { ar: "حساب السعرات الحرارية المثالية...", en: "Calculating ideal calories..." },
    loading5: { ar: "مراجعة الخطة الغذائية...", en: "Reviewing nutrition plan..." },
    loading6: { ar: "اللمسات الأخيرة قبل إرسالها...", en: "Final touches before sending..." },
  }
};

// New unified country list – one Arabic name, one English name, one flag
export const COUNTRIES = [
  { nameAr: "مصر", nameEn: "Egypt", flag: "🇪🇬" },
  { nameAr: "الكويت", nameEn: "Kuwait", flag: "🇰🇼" },
  { nameAr: "المملكة العربية السعودية", nameEn: "Saudi Arabia", flag: "🇸🇦" },
  { nameAr: "الإمارات العربية المتحدة", nameEn: "United Arab Emirates", flag: "🇦🇪" },
  { nameAr: "قطر", nameEn: "Qatar", flag: "🇶🇦" },
  { nameAr: "البحرين", nameEn: "Bahrain", flag: "🇧🇭" },
  { nameAr: "الأردن", nameEn: "Jordan", flag: "🇯🇴" },
  { nameAr: "لبنان", nameEn: "Lebanon", flag: "🇱🇧" },
  { nameAr: "سوريا", nameEn: "Syria", flag: "🇸🇾" },
  { nameAr: "العراق", nameEn: "Iraq", flag: "🇮🇶" },
  { nameAr: "اليمن", nameEn: "Yemen", flag: "🇾🇪" },
  { nameAr: "عُمان", nameEn: "Oman", flag: "🇴🇲" },
  { nameAr: "المغرب", nameEn: "Morocco", flag: "🇲🇦" },
  { nameAr: "تونس", nameEn: "Tunisia", flag: "🇹🇳" },
  { nameAr: "الجزائر", nameEn: "Algeria", flag: "🇩🇿" },
  { nameAr: "ليبيا", nameEn: "Libya", flag: "🇱🇾" },
  { nameAr: "السودان", nameEn: "Sudan", flag: "🇸🇩" },
  { nameAr: "الصومال", nameEn: "Somalia", flag: "🇸🇴" },
  { nameAr: "موريتانيا", nameEn: "Mauritania", flag: "🇲🇷" },
  { nameAr: "جيبوتي", nameEn: "Djibouti", flag: "🇩🇯" },
  { nameAr: "جزر القمر", nameEn: "Comoros", flag: "🇰🇲" },
  { nameAr: "فلسطين", nameEn: "Palestine", flag: "🇵🇸" },
  { nameAr: "المملكة المتحدة", nameEn: "United Kingdom", flag: "🇬🇧" },
  { nameAr: "الولايات المتحدة الأمريكية", nameEn: "United States", flag: "🇺🇸" },
  { nameAr: "كندا", nameEn: "Canada", flag: "🇨🇦" },
  { nameAr: "أستراليا", nameEn: "Australia", flag: "🇦🇺" },
  { nameAr: "فرنسا", nameEn: "France", flag: "🇫🇷" },
  { nameAr: "ألمانيا", nameEn: "Germany", flag: "🇩🇪" },
  { nameAr: "إيطاليا", nameEn: "Italy", flag: "🇮🇹" },
  { nameAr: "إسبانيا", nameEn: "Spain", flag: "🇪🇸" },
  { nameAr: "هولندا", nameEn: "Netherlands", flag: "🇳🇱" },
  { nameAr: "بلجيكا", nameEn: "Belgium", flag: "🇧🇪" },
  { nameAr: "السويد", nameEn: "Sweden", flag: "🇸🇪" },
  { nameAr: "النرويج", nameEn: "Norway", flag: "🇳🇴" },
  { nameAr: "الدنمارك", nameEn: "Denmark", flag: "🇩🇰" },
  { nameAr: "فنلندا", nameEn: "Finland", flag: "🇫🇮" },
  { nameAr: "سويسرا", nameEn: "Switzerland", flag: "🇨🇭" },
  { nameAr: "النمسا", nameEn: "Austria", flag: "🇦🇹" },
  { nameAr: "البرتغال", nameEn: "Portugal", flag: "🇵🇹" },
  { nameAr: "اليونان", nameEn: "Greece", flag: "🇬🇷" },
  { nameAr: "تركيا", nameEn: "Turkey", flag: "🇹🇷" },
  { nameAr: "روسيا", nameEn: "Russia", flag: "🇷🇺" },
  { nameAr: "الصين", nameEn: "China", flag: "🇨🇳" },
  { nameAr: "اليابان", nameEn: "Japan", flag: "🇯🇵" },
  { nameAr: "كوريا الجنوبية", nameEn: "South Korea", flag: "🇰🇷" },
  { nameAr: "الهند", nameEn: "India", flag: "🇮🇳" },
  { nameAr: "باكستان", nameEn: "Pakistan", flag: "🇵🇰" },
  { nameAr: "بنغلاديش", nameEn: "Bangladesh", flag: "🇧🇩" },
  { nameAr: "إندونيسيا", nameEn: "Indonesia", flag: "🇮🇩" },
  { nameAr: "ماليزيا", nameEn: "Malaysia", flag: "🇲🇾" },
  { nameAr: "سنغافورة", nameEn: "Singapore", flag: "🇸🇬" },
  { nameAr: "الفلبين", nameEn: "Philippines", flag: "🇵🇭" },
  { nameAr: "تايلاند", nameEn: "Thailand", flag: "🇹🇭" },
  { nameAr: "إيران", nameEn: "Iran", flag: "🇮🇷" },
  { nameAr: "أفغانستان", nameEn: "Afghanistan", flag: "🇦🇫" },
  { nameAr: "نيجيريا", nameEn: "Nigeria", flag: "🇳🇬" },
  { nameAr: "كينيا", nameEn: "Kenya", flag: "🇰🇪" },
  { nameAr: "إثيوبيا", nameEn: "Ethiopia", flag: "🇪🇹" },
  { nameAr: "غانا", nameEn: "Ghana", flag: "🇬🇭" },
  { nameAr: "جنوب أفريقيا", nameEn: "South Africa", flag: "🇿🇦" },
  { nameAr: "البرازيل", nameEn: "Brazil", flag: "🇧🇷" },
  { nameAr: "الأرجنتين", nameEn: "Argentina", flag: "🇦🇷" },
  { nameAr: "المكسيك", nameEn: "Mexico", flag: "🇲🇽" },
  { nameAr: "ألبانيا", nameEn: "Albania", flag: "🇦🇱" },
  { nameAr: "أرمينيا", nameEn: "Armenia", flag: "🇦🇲" },
  { nameAr: "أذربيجان", nameEn: "Azerbaijan", flag: "🇦🇿" },
  { nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { nameAr: "كرواتيا", nameEn: "Croatia", flag: "🇭🇷" },
  { nameAr: "التشيك", nameEn: "Czech Republic", flag: "🇨🇿" },
  { nameAr: "المجر", nameEn: "Hungary", flag: "🇭🇺" },
  { nameAr: "بولندا", nameEn: "Poland", flag: "🇵🇱" },
  { nameAr: "رومانيا", nameEn: "Romania", flag: "🇷🇴" },
  { nameAr: "أوكرانيا", nameEn: "Ukraine", flag: "🇺🇦" },
  { nameAr: "أيرلندا", nameEn: "Ireland", flag: "🇮🇪" },
  { nameAr: "نيوزيلندا", nameEn: "New Zealand", flag: "🇳🇿" },
  { nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan", flag: "🇰🇬" },
  { nameAr: "كازاخستان", nameEn: "Kazakhstan", flag: "🇰🇿" },
  { nameAr: "أوزبكستان", nameEn: "Uzbekistan", flag: "🇺🇿" },
  { nameAr: "تركمانستان", nameEn: "Turkmenistan", flag: "🇹🇲" },
  { nameAr: "طاجيكستان", nameEn: "Tajikistan", flag: "🇹🇯" },
  { nameAr: "جورجيا", nameEn: "Georgia", flag: "🇬🇪" },
  { nameAr: "إريتريا", nameEn: "Eritrea", flag: "🇪🇷" },
  { nameAr: "رواندا", nameEn: "Rwanda", flag: "🇷🇼" },
  { nameAr: "أوغندا", nameEn: "Uganda", flag: "🇺🇬" },
  { nameAr: "تنزانيا", nameEn: "Tanzania", flag: "🇹🇿" },
  { nameAr: "زيمبابوي", nameEn: "Zimbabwe", flag: "🇿🇼" },
  { nameAr: "زامبيا", nameEn: "Zambia", flag: "🇿🇲" },
  { nameAr: "موزمبيق", nameEn: "Mozambique", flag: "🇲🇿" },
  { nameAr: "مدغشقر", nameEn: "Madagascar", flag: "🇲🇬" },
  { nameAr: "الكاميرون", nameEn: "Cameroon", flag: "🇨🇲" },
  { nameAr: "السنغال", nameEn: "Senegal", flag: "🇸🇳" },
  { nameAr: "ساحل العاج", nameEn: "Ivory Coast", flag: "🇨🇮" },
  { nameAr: "فيتنام", nameEn: "Vietnam", flag: "🇻🇳" },
  { nameAr: "كمبوديا", nameEn: "Cambodia", flag: "🇰🇭" },
  { nameAr: "ميانمار", nameEn: "Myanmar", flag: "🇲🇲" },
  { nameAr: "سريلانكا", nameEn: "Sri Lanka", flag: "🇱🇰" },
  { nameAr: "نيبال", nameEn: "Nepal", flag: "🇳🇵" },
  { nameAr: "كولومبيا", nameEn: "Colombia", flag: "🇨🇴" },
  { nameAr: "بيرو", nameEn: "Peru", flag: "🇵🇪" },
  { nameAr: "شيلي", nameEn: "Chile", flag: "🇨🇱" },
  { nameAr: "فنزويلا", nameEn: "Venezuela", flag: "🇻🇪" },
  { nameAr: "كوبا", nameEn: "Cuba", flag: "🇨🇺" },
  { nameAr: "الدومينيكان", nameEn: "Dominican Republic", flag: "🇩🇴" },
  { nameAr: "بوليفيا", nameEn: "Bolivia", flag: "🇧🇴" },
  { nameAr: "باراغواي", nameEn: "Paraguay", flag: "🇵🇾" },
  { nameAr: "أوروغواي", nameEn: "Uruguay", flag: "🇺🇾" },
];
