export const C = {
  bg: "#0B0F19",
  card: "#151C2C",
  cardLight: "#1E293B",
  border: "#334155",
  teal: "#145952",
  tealDark: "#0C3F3A",
  tealGlow: "#14595225",
  amber: "#C2952A",
  amberGlow: "#C2952A25",
  text: "#F8FAFC",
  muted: "#94A3B8",
  danger: "#EF4444",
  green: "#145952",
  greenDark: "#0C3F3A",
  purple: "#8B5CF6",
};

export const T = {
  landing: {
    badge: { ar: "✦ أفضل متخصصي التغذية في الشرق الأوسط — بين يديك", en: "✦ Top Nutrition Specialists in the Middle East — At Your Fingertips" },
    heading1: { ar: "خبرة حقيقية في التغذية", en: "Real Nutrition Expertise" },
    heading2: { ar: "مدعومة بأحدث تقنيات الذكاء الاصطناعي", en: "Powered by Advanced AI Technology" },
    desc: { ar: "متخصصو تغذية معتمدون بخبرة تمتد لسنوات، يستخدمون الذكاء الاصطناعي لبناء خطتك الغذائية بدقة لا مثيل لها.", en: "Certified nutrition specialists with years of experience use AI to build your personalized nutrition plan with unmatched precision." },
    warning: { ar: "⚠️ ملاحظة مهمة: بيانات صحتك وأمراضك وأدويتك ضرورية لضمان سلامة خطتك.", en: "⚠️ Important: Your health data, conditions, and medications are essential to ensure your plan's safety." },
    cta: { ar: "ابدأ الاستبيان المجاني ←", en: "Start Free Questionnaire →" },
    time: { ar: "3 دقائق فقط · بدون تسجيل · بدون دفع مسبق", en: "Just 3 minutes · No registration · No upfront payment" },
    staff: { ar: "دخول الموظفين", en: "Staff Login" },
    aiPowered: { ar: "مدعوم بالذكاء الاصطناعي", en: "AI-Powered" },
    features: [
      { icon: "🏅", title: { ar: "متخصصون معتمدون", en: "Certified Specialists" }, desc: { ar: "متخصصو تغذية بخبرة سنوات في الشرق الأوسط", en: "Nutrition specialists with years of experience in the Middle East" } },
      { icon: "🤖", title: { ar: "مدعومون بالذكاء الاصطناعي", en: "AI-Powered" }, desc: { ar: "تقنية متقدمة لخطة دقيقة لجسمك وبلدك", en: "Advanced tech for a precise plan for your body and country" } },
      { icon: "💳", title: { ar: "الدفع على النتيجة", en: "Pay for Results" }, desc: { ar: "تدفع أسبوعياً فقط عند تحقيق تقدم", en: "Pay weekly only when you see progress" } },
      { icon: "🔄", title: { ar: "متابعة أسبوعية", en: "Weekly Follow-up" }, desc: { ar: "متخصصك يعدل خطتك كل أسبوع", en: "Your specialist adjusts your plan every week" } }
    ],
    steps: { ar: "آلية عمل النظام", en: "How It Works" },
    stepsList: [
      { title: { ar: "أجب على استبيان شامل", en: "Complete a Comprehensive Questionnaire" }, desc: { ar: "3 دقائق تغطي صحتك وعاداتك", en: "3 minutes covering your health and habits" } },
      { title: { ar: "الذكاء الاصطناعي يبني مسوّدة خطتك", en: "AI Builds Your Plan Draft" }, desc: { ar: "وجبات مخصصة لجسمك وبلدك في ثوانٍ", en: "Meals tailored to your body and country in seconds" } },
      { title: { ar: "متخصصنا يراجع ويوافق", en: "Our Specialist Reviews & Approves" }, desc: { ar: "خبرة بشرية تراجع كل تفصيلة", en: "Human expertise reviews every detail" } },
      { title: { ar: "متابعة أسبوعية وتعديل مستمر", en: "Real Weekly Follow-up & Continuous Adjustment" }, desc: { ar: "كل أسبوع تُرسل نتائجك، ومتخصصك يعدّل خطتك", en: "Each week you send your results, your specialist adjusts your plan" } }
    ]
  },
  login: {
    title: { ar: "دخول الموظفين", en: "Staff Login" },
    hint: { ar: "أدخل رمز الدخول الخاص بك. (admin123 للمدير، spec123 للمتخصص)", en: "Enter your access code. (admin123 for admin, spec123 for specialist)" },
    loginBtn: { ar: "تسجيل الدخول", en: "Login" },
    back: { ar: "العودة كعميل", en: "Back as Customer" },
    error: { ar: "رمز الدخول غير صحيح!", en: "Invalid access code!" }
  },
  quiz: {
    question: { ar: "السؤال", en: "Question" },
    of: { ar: "من", en: "of" },
    optional: { ar: "اختياري", en: "Optional" },
    back: { ar: "← رجوع", en: "← Back" },
    next: { ar: "التالي ←", en: "Next →" },
    generate: { ar: "🚀 أنشئ خطتي بالذكاء الاصطناعي", en: "🚀 Generate My AI Plan" },
    phoneHint: { ar: "يرجى إدخال رقم هاتف صحيح", en: "Please enter a valid phone number" },
    multiHint: { ar: "يمكنك اختيار أكثر من إجابة", en: "You can select multiple answers" },
    healthNoteTitle: { ar: "📝 تفاصيل إضافية عن وضعك الصحي", en: "📝 Additional Health Details" },
    healthNoteSent: { ar: "✓ ستُرسل هذه المعلومات إلى المتخصص مباشرة", en: "✓ This information will be sent directly to the specialist" },
    healthyWeight: { ar: "الوزن الصحي المثالي حسب طولك", en: "Healthy Ideal Weight for Your Height" },
    healthyRange: { ar: "النطاق الصحي", en: "Healthy Range" },
    customTarget: { ar: "أختار هدفي بنفسي", en: "Choose My Own Goal" },
    currentStatus: { ar: "وضعك الحالي", en: "Your Current Status" },
    bmi: { ar: "مؤشر كتلة الجسم", en: "Body Mass Index" },
    popularCountries: { ar: "الأكثر شيوعاً", en: "Most Popular" },
    noResults: { ar: "لا توجد نتائج — جرّب كتابة مختلفة", en: "No results — Try a different search" }
  },
  generating: {
    title: { ar: "متخصصنا يبني خطتك...", en: "Our Specialist is Building Your Plan..." },
    time: { ar: "يستغرق عادةً من 15 إلى 30 ثانية", en: "Usually takes 15 to 30 seconds" }
  },
  error: {
    rateLimit: { ar: "الخدمة مشغولة مؤقتاً", en: "Service Temporarily Busy" },
    rateLimitDesc: { ar: "وصلنا للحد الأقصى للاستخدام. انتظر بضع دقائق وحاول مجدداً.", en: "Usage limit reached. Wait a few minutes and try again." },
    general: { ar: "تعذّر توليد الخطة", en: "Failed to Generate Plan" },
    generalDesc: { ar: "حدث خطأ أثناء التوليد. تحقق من اتصالك بالإنترنت وحاول مجدداً.", en: "An error occurred during generation. Check your internet connection and try again." },
    details: { ar: "تفاصيل الخطأ", en: "Error Details" },
    retry: { ar: "حاول مجدداً ←", en: "Try Again →" },
    restart: { ar: "البداية من جديد", en: "Start Over" }
  },
  plan: {
    pending: { ar: "⏳ بانتظار موافقة المتخصص", en: "⏳ Awaiting Specialist Approval" },
    ready: { ar: "✦ خطتك جاهزة وقيد المراجعة", en: "✦ Your Plan is Ready and Under Review" },
    hello: { ar: "مرحباً", en: "Hello" },
    contact: { ar: "سيتواصل معك المتخصص قريباً", en: "Specialist will contact you soon" },
    level: { ar: "المستوى", en: "Level" },
    points: { ar: "نقطة (XP)", en: "Points (XP)" },
    streak: { ar: "شعلة الالتزام", en: "Commitment Streak" },
    calories: { ar: "سعرة / يوم", en: "cal/day" },
    goal: { ar: "الهدف المقرر", en: "Target Goal" },
    protein: { ar: "بروتين", en: "Protein" },
    carbs: { ar: "كربوهيدرات", en: "Carbs" },
    fats: { ar: "دهون", en: "Fats" },
    weeklyPlan: { ar: "📅 الخطة الأسبوعية", en: "📅 Weekly Plan" },
    preview: { ar: "— معاينة مجانية ليوم واحد 🔒", en: "— Free Preview for One Day 🔒" },
    breakfast: { ar: "🌅 الفطور", en: "🌅 Breakfast" },
    lunch: { ar: "☀️ الغداء", en: "☀️ Lunch" },
    dinner: { ar: "🌙 العشاء", en: "🌙 Dinner" },
    snack: { ar: "🍎 وجبة خفيفة", en: "🍎 Snack" },
    chooseOne: { ar: "💡 اختر بديلاً واحداً فقط لكل وجبة", en: "💡 Choose only one alternative per meal" },
    or: { ar: "أو", en: "Or" },
    locked: { ar: "🔒 باقي المحتوى مقفول", en: "🔒 Remaining content locked" },
    lockedDesc: { ar: "ادفع الآن لفتح جميع الوجبات، التمارين المفصلة، والنصائح الكاملة.", en: "Pay now to unlock all meals, detailed workouts, and full tips." },
    workout: { ar: "🏋️ روتين رياضي منزلي", en: "🏋️ Home Workout Routine" },
    tips: { ar: "💡 نصائح مخصصة لك", en: "💡 Personalized Tips" },
    payment: { ar: "💳 إتمام الاشتراك", en: "💳 Complete Subscription" },
    paymentDesc: { ar: "خطتك جاهزة وتمت مراجعتها. جرّب الأسبوع الأول — إن أحسست بفرق حقيقي، استمر.", en: "Your plan is ready and reviewed. Try the first week — if you feel a real difference, continue." },
    weekFee: { ar: "رسوم الأسبوع", en: "Week Fee" },
    payWeekly: { ar: "يُدفع أسبوعاً بعد أسبوع فقط", en: "Paid weekly only" },
    paid: { ar: "✅ تم الدفع بنجاح — تم تفعيل الخطة كاملة!", en: "✅ Payment Successful — Full Plan Activated!" },
    receipt: { ar: "رقم الإيصال", en: "Receipt Number" },
    sending: { ar: "جاري إرسال الخطة الأسبوعية عبر واتساب...", en: "Sending weekly plan via WhatsApp..." },
    sent: { ar: "📱 تم إرسال الخطة بنجاح إلى رقمك!", en: "📱 Plan sent successfully to your number!" },
    payBtn: { ar: "ادفع الآن عبر PayPal", en: "Pay Now via PayPal" },
    paying: { ar: "جارٍ تأكيد الدفع...", en: "Confirming payment..." },
    secure: { ar: "🔒 دفع آمن عبر PayPal · لا تُحفظ بيانات بطاقتك", en: "🔒 Secure PayPal payment · Your card details are not stored" },
    specialistPanel: { ar: "⚕️ لوحة المتخصص", en: "⚕️ Specialist Panel" },
    admin: { ar: "(مدير)", en: "(Admin)" },
    medicalNotes: { ar: "📝 ملاحظات طبية — للمتخصص فقط", en: "📝 Medical Notes — For Specialist Only" },
    patientNotes: { ar: "📝 ملاحظات المريض بكلامه", en: "📝 Patient Notes in Their Own Words" },
    approve: { ar: "✅ اعتماد الخطة والموافقة عليها", en: "✅ Approve and Confirm Plan" },
    approved: { ar: "✓ تمت الموافقة على الخطة", en: "✓ Plan Approved" },
    backend: { ar: "🔄 تتبع النظام الآلي (Backend Status)", en: "🔄 Backend Status Tracking" },
    paymentStatus: { ar: "حالة الدفع", en: "Payment Status" },
    paidStatus: { ar: "تم الدفع بنجاح", en: "Payment Successful" },
    waitingPayment: { ar: "بانتظار الدفع...", en: "Awaiting Payment..." },
    whatsappStatus: { ar: "إرسال واتساب", en: "WhatsApp Sending" },
    whatsappSentStatus: { ar: "تم الإرسال آلياً عبر Cloud API", en: "Sent automatically via Cloud API" },
    dailyFollowup: { ar: "🔔 متابعة يومية (واتساب - يدوية مؤقتاً)", en: "🔔 Daily Follow-up (WhatsApp - Manual for now)" },
    followupNote: { ar: "سيتم ربطها آلياً عبر Firebase Functions لاحقاً", en: "Will be automated via Firebase Functions later" },
    morningMsg: { ar: "🌅 رسالة الصباح الترحيبية", en: "🌅 Morning Welcome Message" },
    middayMsg: { ar: "☀️ متابعة منتصف اليوم", en: "☀️ Midday Follow-up" },
    eveningMsg: { ar: "🌙 رسالة المساء التحفيزية", en: "🌙 Evening Motivational Message" },
    followupWeek: { ar: "📅 هل مرّ أسبوع على البرنامج؟", en: "📅 Has a Week Passed?" },
    followupDesc: { ar: "أرسل لي نتائجك وسأعدّل خطتك للأسبوع القادم بناءً على تقدمك الفعلي", en: "Send me your results and I'll adjust your plan for next week based on your actual progress" },
    followupBtn: { ar: "متابعة الأسبوع", en: "Follow-up Week" },
    restart: { ar: "← البداية من جديد", en: "← Start Over" },
    your_info: { ar: "📋 معلوماتك", en: "📋 Your Info" },
    age: { ar: "العمر", en: "Age" },
    gender: { ar: "الجنس", en: "Gender" },
    height: { ar: "الطول", en: "Height" },
    weight: { ar: "الوزن", en: "Weight" },
    target: { ar: "الهدف", en: "Target" },
    bmi: { ar: "مؤشر كتلة الجسم", en: "BMI" },
    conditions: { ar: "حالات صحية", en: "Conditions" },
    allergies: { ar: "حساسيات", en: "Allergies" },
    activity: { ar: "نشاط بدني", en: "Activity" },
    food_pref: { ar: "تفضيلات طعام", en: "Food Preferences" },
    country: { ar: "البلد", en: "Country" }
  },
  followup: {
    title: { ar: "متابعة الأسبوع", en: "Week Follow-up" },
    questions: [
      { id: "new_weight", icon: "⚖️", title: { ar: "كم وزنك اليوم؟", en: "What's your weight today?" }, sub: { ar: "قِسه الآن قبل الإجابة للدقة", en: "Measure it now before answering for accuracy" }, type: "number", unit: { ar: "كجم", en: "kg" }, required: true },
      { id: "adherence", icon: "📋", title: { ar: "كم يوماً التزمت بالخطة الغذائية؟", en: "How many days did you stick to the plan?" }, sub: { ar: "كن صادقاً — هذا يساعدني في تعديل خطتك", en: "Be honest — this helps me adjust your plan" }, type: "choice", options: { ar: ["7 أيام كاملة 🏆", "5 إلى 6 أيام ✅", "3 إلى 4 أيام 😐", "يوم أو يومان 😕", "لم أستطع الالتزام 😞"], en: ["7 Full Days 🏆", "5-6 Days ✅", "3-4 Days 😐", "1-2 Days 😕", "Couldn't Commit 😞"] }, required: true },
      { id: "hard_meals", icon: "🍽️", title: { ar: "أي وجبة كانت الأصعب في التطبيق؟", en: "Which meal was hardest to follow?" }, sub: { ar: "سأغيّرها لك في الأسبوع القادم", en: "I'll change it for you next week" }, type: "choice", options: { ar: ["الفطور", "الغداء", "العشاء", "الوجبة الخفيفة", "لم تكن هناك صعوبة"], en: ["Breakfast", "Lunch", "Dinner", "Snack", "No Difficulty"] }, required: true },
      { id: "energy", icon: "⚡", title: { ar: "كيف كان مستوى طاقتك خلال الأسبوع؟", en: "How was your energy level this week?" }, sub: { ar: "الطاقة المنخفضة تعني أن السعرات تحتاج تعديلاً", en: "Low energy means calories need adjustment" }, type: "choice", options: { ar: ["ممتاز — نشيط طوال الوقت 💪", "جيد — بشكل عام مقبول 😊", "متذبذب — أحياناً تعب 😐", "منخفض — تعبت كثيراً 😔", "منهك جداً 🔴"], en: ["Excellent — Energetic All Day 💪", "Good — Generally Okay 😊", "Fluctuating — Sometimes Tired 😐", "Low — Very Tired 😔", "Exhausted 🔴"] }, required: true },
      { id: "side_effects", icon: "🩺", title: { ar: "هل لاحظت أي أعراض جسدية هذا الأسبوع؟", en: "Did you notice any physical symptoms this week?" }, sub: { ar: "أي شيء غير معتاد يهمني أن أعرفه", en: "Anything unusual, I need to know" }, type: "multichoice", options: { ar: ["لا شيء — كل شيء طبيعي ✅", "صداع متكرر", "دوخة أو إغماء", "إمساك أو اضطراب هضمي", "نوم مضطرب", "جوع شديد", "آخر"], en: ["Nothing — All Normal ✅", "Frequent Headaches", "Dizziness or Fainting", "Constipation or Digestive Issues", "Disturbed Sleep", "Extreme Hunger", "Other"] }, required: true },
      { id: "notes", icon: "💬", title: { ar: "هل ثمة شيء تريد إخباري به؟", en: "Is there anything you want to tell me?" }, sub: { ar: "أي ملاحظة أو تغيير في حياتك أو صحتك هذا الأسبوع", en: "Any notes or changes in your life or health this week" }, type: "textarea", required: false }
    ],
    progress: { ar: "السؤال", en: "Question" },
    generateBtn: { ar: "🚀 أنشئ خطة الأسبوع الجديد", en: "🚀 Generate New Week Plan" }
  },
  community: {
    title: { ar: "🌍 المجتمع", en: "🌍 Community" },
    leaderboard: { ar: "🏆 المتصدرون", en: "🏆 Leaderboard" },
    follow: { ar: "متابعة", en: "Follow" },
    unfollow: { ar: "إلغاء المتابعة", en: "Unfollow" },
    posts: { ar: "📸 منشورات التحول", en: "📸 Transformations" },
    postPlaceholder: { ar: "اكتب تعليقاً عن تقدمك...", en: "Write a comment about your progress..." },
    uploadPhoto: { ar: "📷 أضف صورة", en: "📷 Add Photo" },
    publish: { ar: "نشر", en: "Publish" },
    beforeAfter: { ar: "قبل / بعد", en: "Before / After" }
  },
  profile: {
    title: { ar: "الملف الشخصي", en: "Profile" },
    xp: { ar: "نقاط الخبرة", en: "XP" },
    streak: { ar: "الشعلة", en: "Streak" },
    level: { ar: "المستوى", en: "Level" },
    badges: { ar: "شارات", en: "Badges" }
  },
  questions: [
    { id: "first_name", type: "text", label: { ar: "اسمك الأول؟", en: "Your first name?" }, placeholder: { ar: "أدخل اسمك", en: "Enter your name" }, icon: "👤", required: true },
    { id: "phone", type: "tel", label: { ar: "رقم هاتفك (اختياري)", en: "Phone number (optional)" }, placeholder: { ar: "مثال: 0096599001234", en: "Example: 0096599001234" }, icon: "📱", required: false, hint: { ar: "لن نزعجك، فقط للمتابعة الأسبوعية", en: "We'll only use it for weekly follow-up" } },
    { id: "age", type: "number", label: { ar: "كم عمرك؟", en: "How old are you?" }, placeholder: { ar: "مثال: 30", en: "Example: 30" }, unit: { ar: "سنة", en: "years" }, icon: "🎂", required: true },
    { id: "gender", type: "choice", label: { ar: "الجنس", en: "Gender" }, options: { ar: ["ذكر", "أنثى"], en: ["Male", "Female"] }, icon: "⚧", required: true },
    { id: "height", type: "number", label: { ar: "طولك (سم)", en: "Your height (cm)" }, placeholder: { ar: "مثال: 170", en: "Example: 170" }, unit: { ar: "سم", en: "cm" }, icon: "📏", required: true },
    { id: "current_weight", type: "number", label: { ar: "وزنك الحالي (كجم)", en: "Current weight (kg)" }, placeholder: { ar: "مثال: 90", en: "Example: 90" }, unit: { ar: "كجم", en: "kg" }, icon: "⚖️", required: true },
    { id: "target_weight", type: "smart_target", label: { ar: "الوزن المستهدف", en: "Target weight" }, icon: "🎯", required: true },
    {
      id: "health_conditions", type: "multichoice_notes",
      label: { ar: "أمراض مزمنة أو أدوية؟", en: "Chronic diseases or medications?" },
      options: { ar: ["لا يوجد", "سكري", "ضغط", "قلب", "غدة", "كلى", "كبد", "أخرى"], en: ["None", "Diabetes", "Hypertension", "Heart", "Thyroid", "Kidney", "Liver", "Other"] },
      icon: "🏥", required: true,
      warn: { ar: "هذه المعلومات ضرورية لسلامتك", en: "This info is essential for your safety" },
      notePlaceholder: { ar: "اكتب الأمراض والأدوية بالتفصيل...", en: "List any diseases & medications..." }
    },
    {
      id: "allergies", type: "multichoice_notes",
      label: { ar: "حساسية أو أطعمة ممنوعة؟", en: "Allergies / forbidden foods?" },
      options: { ar: ["لا يوجد", "لاكتوز", "جلوتين", "مكسرات", "بيض", "بحريات", "أخرى"], en: ["None", "Lactose", "Gluten", "Nuts", "Eggs", "Seafood", "Other"] },
      icon: "⚠️",
      notePlaceholder: { ar: "أي أطعمة لا تتحملها؟", en: "Any foods you can't eat?" }
    },
    {
      id: "activity", type: "choice",
      label: { ar: "مستوى نشاطك البدني", en: "Physical activity level" },
      options: { ar: ["لا أمارس رياضة", "خفيف (مرة بالأسبوع)", "متوسط (3 مرات)", "عالي (يوميًا)"], en: ["Sedentary (no exercise)", "Light (1x/week)", "Moderate (3x/week)", "Active (daily)"] },
      icon: "🏃"
    },
    {
      id: "food_pref", type: "multichoice",
      label: { ar: "تفضيلاتك الغذائية", en: "Your food preferences" },
      options: { ar: ["آكل كل شيء", "نباتي", "دجاج وسمك فقط", "لحوم حمراء", "لا أحب الخضروات"], en: ["Eat everything", "Vegetarian", "Chicken & Fish only", "Red meat", "Don't like vegetables"] },
      icon: "🥗"
    },
    { id: "country", type: "country_search", label: { ar: "دولة إقامتك", en: "Your country" }, placeholder: { ar: "ابحث عن دولتك...", en: "Search your country..." }, icon: "🌍", required: true },
  ],
  common: {
    loading: { ar: "جارٍ تحليل بياناتك...", en: "Analyzing your data..." },
    loading2: { ar: "متخصصنا يدرس ملفك الصحي...", en: "Our specialist is reviewing your health file..." },
    loading3: { ar: "تخصيص الوجبات حسب جسمك وبلدك...", en: "Customizing meals for your body and country..." },
    loading4: { ar: "حساب السعرات الحرارية المثالية...", en: "Calculating ideal calories..." },
    loading5: { ar: "مراجعة الخطة الغذائية...", en: "Reviewing nutrition plan..." },
    loading6: { ar: "اللمسات الأخيرة قبل إرسالها...", en: "Final touches before sending..." },
  }
};

export const COUNTRY_DATA = [
  { name: "مصر", aliases: ["مصر", "egypt", "ايجبت"] },
  { name: "الكويت", aliases: ["الكويت", "كويت", "kuwait"] },
  { name: "المملكة العربية السعودية", aliases: ["السعودية", "المملكة", "سعودية", "الرياض", "saudi", "ksa", "saudi arabia"] },
  { name: "الإمارات العربية المتحدة", aliases: ["الامارات", "الإمارات", "دبي", "ابوظبي", "أبوظبي", "uae", "dubai", "emirates"] },
  { name: "قطر", aliases: ["قطر", "الدوحة", "qatar", "doha"] },
  { name: "البحرين", aliases: ["البحرين", "بحرين", "bahrain", "المنامة"] },
  { name: "الأردن", aliases: ["الأردن", "اردن", "عمان", "jordan", "amman"] },
  { name: "لبنان", aliases: ["لبنان", "بيروت", "lebanon", "beirut"] },
  { name: "سوريا", aliases: ["سوريا", "دمشق", "syria", "damascus"] },
  { name: "العراق", aliases: ["العراق", "عراق", "بغداد", "iraq", "baghdad"] },
  { name: "اليمن", aliases: ["اليمن", "يمن", "صنعاء", "yemen", "sanaa"] },
  { name: "عُمان", aliases: ["عمان", "سلطنة عمان", "مسقط", "oman", "muscat"] },
  { name: "المغرب", aliases: ["المغرب", "مغرب", "الرباط", "الدار البيضاء", "morocco", "maroc", "casablanca"] },
  { name: "تونس", aliases: ["تونس", "تونس العاصمة", "tunisia"] },
  { name: "الجزائر", aliases: ["الجزائر", "جزائر", "algeria"] },
  { name: "ليبيا", aliases: ["ليبيا", "طرابلس", "libya", "tripoli"] },
  { name: "السودان", aliases: ["السودان", "سودان", "الخرطوم", "sudan", "khartoum"] },
  { name: "الصومال", aliases: ["الصومال", "صومال", "مقديشو", "somalia", "mogadishu"] },
  { name: "موريتانيا", aliases: ["موريتانيا", "نواكشوط", "mauritania"] },
  { name: "جيبوتي", aliases: ["جيبوتي", "djibouti"] },
  { name: "جزر القمر", aliases: ["جزر القمر", "comoros"] },
  { name: "فلسطين", aliases: ["فلسطين", "غزة", "الضفة", "palestine", "gaza"] },
  { name: "المملكة المتحدة", aliases: ["المملكة المتحدة", "انجلترا", "إنجلترا", "بريطانيا", "لندن", "uk", "england", "britain", "great britain", "united kingdom", "london"] },
  { name: "الولايات المتحدة الأمريكية", aliases: ["الولايات المتحدة", "أمريكا", "امريكا", "نيويورك", "usa", "us", "america", "united states", "new york"] },
  { name: "كندا", aliases: ["كندا", "canada", "toronto", "montreal"] },
  { name: "أستراليا", aliases: ["استراليا", "أستراليا", "australia", "sydney", "melbourne"] },
  { name: "فرنسا", aliases: ["فرنسا", "باريس", "france", "paris"] },
  { name: "ألمانيا", aliases: ["المانيا", "ألمانيا", "برلين", "germany", "berlin"] },
  { name: "إيطاليا", aliases: ["ايطاليا", "إيطاليا", "روما", "italy", "rome"] },
  { name: "إسبانيا", aliases: ["اسبانيا", "إسبانيا", "مدريد", "spain", "madrid"] },
  { name: "هولندا", aliases: ["هولندا", "امستردام", "netherlands", "amsterdam", "holland"] },
  { name: "بلجيكا", aliases: ["بلجيكا", "بروكسل", "belgium", "brussels"] },
  { name: "السويد", aliases: ["السويد", "ستوكهولم", "sweden", "stockholm"] },
  { name: "النرويج", aliases: ["النرويج", "اوسلو", "norway", "oslo"] },
  { name: "الدنمارك", aliases: ["الدنمارك", "كوبنهاغن", "denmark", "copenhagen"] },
  { name: "فنلندا", aliases: ["فنلندا", "هلسنكي", "finland", "helsinki"] },
  { name: "سويسرا", aliases: ["سويسرا", "جنيف", "زيورخ", "switzerland", "geneva", "zurich"] },
  { name: "النمسا", aliases: ["النمسا", "فيينا", "austria", "vienna"] },
  { name: "البرتغال", aliases: ["البرتغال", "لشبونة", "portugal", "lisbon"] },
  { name: "اليونان", aliases: ["اليونان", "اثينا", "greece", "athens"] },
  { name: "تركيا", aliases: ["تركيا", "اسطنبول", "إسطنبول", "أنقرة", "turkey", "istanbul", "ankara"] },
  { name: "روسيا", aliases: ["روسيا", "موسكو", "russia", "moscow"] },
  { name: "الصين", aliases: ["الصين", "بكين", "شنغهاي", "china", "beijing", "shanghai"] },
  { name: "اليابان", aliases: ["اليابان", "طوكيو", "japan", "tokyo"] },
  { name: "كوريا الجنوبية", aliases: ["كوريا", "كوريا الجنوبية", "سيول", "south korea", "korea", "seoul"] },
  { name: "الهند", aliases: ["الهند", "هند", "نيودلهي", "india", "new delhi", "mumbai"] },
  { name: "باكستان", aliases: ["باكستان", "اسلام اباد", "كراتشي", "pakistan", "islamabad", "karachi"] },
  { name: "بنغلاديش", aliases: ["بنغلاديش", "داكا", "bangladesh", "dhaka"] },
  { name: "إندونيسيا", aliases: ["اندونيسيا", "إندونيسيا", "جاكرتا", "indonesia", "jakarta"] },
  { name: "ماليزيا", aliases: ["ماليزيا", "كوالالمبور", "malaysia", "kuala lumpur", "kl"] },
  { name: "سنغافورة", aliases: ["سنغافورة", "singapore"] },
  { name: "الفلبين", aliases: ["الفلبين", "فلبين", "مانيلا", "philippines", "manila"] },
  { name: "تايلاند", aliases: ["تايلاند", "بانكوك", "thailand", "bangkok"] },
  { name: "إيران", aliases: ["ايران", "إيران", "طهران", "iran", "tehran"] },
  { name: "أفغانستان", aliases: ["افغانستان", "أفغانستان", "كابل", "afghanistan", "kabul"] },
  { name: "نيجيريا", aliases: ["نيجيريا", "لاغوس", "nigeria", "lagos", "abuja"] },
  { name: "كينيا", aliases: ["كينيا", "نيروبي", "kenya", "nairobi"] },
  { name: "إثيوبيا", aliases: ["اثيوبيا", "إثيوبيا", "اديس ابابا", "ethiopia", "addis ababa"] },
  { name: "غانا", aliases: ["غانا", "اكرا", "ghana", "accra"] },
  { name: "جنوب أفريقيا", aliases: ["جنوب افريقيا", "جنوب أفريقيا", "كيب تاون", "جوهانسبرغ", "south africa", "cape town", "johannesburg"] },
  { name: "البرازيل", aliases: ["البرازيل", "برازيل", "ساو باولو", "brazil", "sao paulo", "rio"] },
  { name: "الأرجنتين", aliases: ["الأرجنتين", "أرجنتين", "بوينس أيرس", "argentina", "buenos aires"] },
  { name: "المكسيك", aliases: ["المكسيك", "مكسيك", "mexico", "mexico city"] },
  { name: "ألبانيا", aliases: ["البانيا", "ألبانيا", "albania"] },
  { name: "أرمينيا", aliases: ["ارمينيا", "أرمينيا", "armenia"] },
  { name: "أذربيجان", aliases: ["اذربيجان", "أذربيجان", "azerbaijan", "baku"] },
  { name: "البوسنة والهرسك", aliases: ["البوسنة", "Bosnia"] },
  { name: "كرواتيا", aliases: ["كرواتيا", "croatia", "zagreb"] },
  { name: "التشيك", aliases: ["التشيك", "براغ", "czech", "prague"] },
  { name: "المجر", aliases: ["المجر", "هنغاريا", "budapest", "hungary"] },
  { name: "بولندا", aliases: ["بولندا", "وارسو", "poland", "warsaw"] },
  { name: "رومانيا", aliases: ["رومانيا", "بوخارست", "romania", "bucharest"] },
  { name: "أوكرانيا", aliases: ["اوكرانيا", "أوكرانيا", "كييف", "ukraine", "kyiv"] },
  { name: "أيرلندا", aliases: ["ايرلندا", "أيرلندا", "دبلن", "ireland", "dublin"] },
  { name: "نيوزيلندا", aliases: ["نيوزيلندا", "new zealand", "auckland"] },
  { name: "قيرغيزستان", aliases: ["قيرغيزستان", "kyrgyzstan"] },
  { name: "كازاخستان", aliases: ["كازاخستان", "kazakhstan", "almaty"] },
  { name: "أوزبكستان", aliases: ["اوزبكستان", "أوزبكستان", "uzbekistan", "tashkent"] },
  { name: "تركمانستان", aliases: ["تركمانستان", "turkmenistan"] },
  { name: "طاجيكستان", aliases: ["طاجيكستان", "tajikistan"] },
  { name: "جورجيا", aliases: ["جورجيا", "تبليسي", "georgia", "tbilisi"] },
  { name: "إريتريا", aliases: ["اريتريا", "إريتريا", "eritrea"] },
  { name: "رواندا", aliases: ["رواندا", "rwanda", "kigali"] },
  { name: "أوغندا", aliases: ["اوغندا", "أوغندا", "uganda", "kampala"] },
  { name: "تنزانيا", aliases: ["تنزانيا", "دار السلام", "tanzania", "dar es salaam"] },
  { name: "زيمبابوي", aliases: ["زيمبابوي", "zimbabwe", "harare"] },
  { name: "زامبيا", aliases: ["زامبيا", "zambia", "lusaka"] },
  { name: "موزمبيق", aliases: ["موزمبيق", "mozambique", "maputo"] },
  { name: "مدغشقر", aliases: ["مدغشقر", "madagascar"] },
  { name: "الكاميرون", aliases: ["الكاميرون", "كاميرون", "cameroon", "yaounde"] },
  { name: "السنغال", aliases: ["السنغال", "سنغال", "داكار", "senegal", "dakar"] },
  { name: "ساحل العاج", aliases: ["ساحل العاج", "كوت ديفوار", "ivory coast", "cote d'ivoire", "abidjan"] },
  { name: "فيتنام", aliases: ["فيتنام", "هانوي", "vietnam", "hanoi", "ho chi minh"] },
  { name: "كمبوديا", aliases: ["كمبوديا", "بنوم بنه", "cambodia", "phnom penh"] },
  { name: "ميانمار", aliases: ["ميانمار", "بورما", "myanmar", "burma", "rangoon"] },
  { name: "سريلانكا", aliases: ["سريلانكا", "sri lanka", "colombo"] },
  { name: "نيبال", aliases: ["نيبال", "كاتماندو", "nepal", "kathmandu"] },
  { name: "كولومبيا", aliases: ["كولومبيا", "بوغوتا", "colombia", "bogota"] },
  { name: "بيرو", aliases: ["بيرو", "ليما", "peru", "lima"] },
  { name: "شيلي", aliases: ["شيلي", "سانتياغو", "chile", "santiago"] },
  { name: "فنزويلا", aliases: ["فنزويلا", "كاراكاس", "venezuela", "caracas"] },
  { name: "كوبا", aliases: ["كوبا", "هافانا", "cuba", "havana"] },
  { name: "الدومينيكان", aliases: ["الدومينيكان", "جمهورية الدومينيكان", "dominican republic", "santo domingo"] },
  { name: "بوليفيا", aliases: ["بوليفيا", "لاباز", "bolivia", "la paz"] },
  { name: "باراغواي", aliases: ["باراغواي", "اسونسيون", "paraguay", "asuncion"] },
  { name: "أوروغواي", aliases: ["اوروغواي", "أوروغواي", "مونتيفيديو", "uruguay", "montevideo"] }
];
