export const C = {
  bg: "#0B0F19",
  card: "#151C2C",
  cardLight: "#1E293B",
  border: "#334155",
  teal: "#145952",
  tealDark: "#0C3F3A",
  tealGlow: "#14595225",
  amber: "#C2952A",
  amberGlow: "#C2952A25",
  text: "#F8FAFC",
  muted: "#94A3B8",
  danger: "#EF4444",
  green: "#145952",
  greenDark: "#0C3F3A",
  purple: "#8B5CF6",
};

export const T = {
  landing: {
    badge: { ar: "✦ أفضل متخصصي التغذية في الشرق الأوسط — بين يديك", en: "✦ Top Nutrition Specialists in the Middle East — At Your Fingertips" },
    heading1: { ar: "خبرة حقيقية في التغذية", en: "Real Nutrition Expertise" },
    heading2: { ar: "مدعومة بأحدث تقنيات الذكاء الاصطناعي", en: "Powered by Advanced AI Technology" },
    desc: { ar: "متخصصو تغذية معتمدون بخبرة تمتد لسنوات، يستخدمون الذكاء الاصطناعي لبناء خطتك الغذائية بدقة لا مثيل لها.", en: "Certified nutrition specialists with years of experience use AI to build your personalized nutrition plan with unmatched precision." },
    warning: { ar: "⚠️ ملاحظة مهمة: بيانات صحتك وأمراضك وأدويتك ضرورية لضمان سلامة خطتك.", en: "⚠️ Important: Your health data, conditions, and medications are essential to ensure your plan's safety." },
    cta: { ar: "ابدأ الاستبيان المجاني ←", en: "Start Free Questionnaire →" },
    time: { ar: "3 دقائق فقط · بدون تسجيل · بدون دفع مسبق", en: "Just 3 minutes · No registration · No upfront payment" },
    staff: { ar: "دخول الموظفين", en: "Staff Login" },
    aiPowered: { ar: "مدعوم بالذكاء الاصطناعي", en: "AI-Powered" },
    features: [
      { icon: "🏅", title: { ar: "متخصصون معتمدون", en: "Certified Specialists" }, desc: { ar: "متخصصو تغذية بخبرة سنوات في الشرق الأوسط", en: "Nutrition specialists with years of experience in the Middle East" } },
      { icon: "🤖", title: { ar: "مدعومون بالذكاء الاصطناعي", en: "AI-Powered" }, desc: { ar: "تقنية متقدمة لخطة دقيقة لجسمك وبلدك", en: "Advanced tech for a precise plan for your body and country" } },
      { icon: "💳", title: { ar: "الدفع على النتيجة", en: "Pay for Results" }, desc: { ar: "تدفع أسبوعياً فقط عند تحقيق تقدم", en: "Pay weekly only when you see progress" } },
      { icon: "🔄", title: { ar: "متابعة أسبوعية", en: "Weekly Follow-up" }, desc: { ar: "متخصصك يعدل خطتك كل أسبوع", en: "Your specialist adjusts your plan every week" } }
    ],
    steps: { ar: "آلية عمل النظام", en: "How It Works" },
    stepsList: [
      { title: { ar: "أجب على استبيان شامل", en: "Complete a Comprehensive Questionnaire" }, desc: { ar: "3 دقائق تغطي صحتك وعاداتك", en: "3 minutes covering your health and habits" } },
      { title: { ar: "الذكاء الاصطناعي يبني مسوّدة خطتك", en: "AI Builds Your Plan Draft" }, desc: { ar: "وجبات مخصصة لجسمك وبلدك في ثوانٍ", en: "Meals tailored to your body and country in seconds" } },
      { title: { ar: "متخصصنا يراجع ويوافق", en: "Our Specialist Reviews & Approves" }, desc: { ar: "خبرة بشرية تراجع كل تفصيلة", en: "Human expertise reviews every detail" } },
      { title: { ar: "متابعة أسبوعية وتعديل مستمر", en: "Real Weekly Follow-up & Continuous Adjustment" }, desc: { ar: "كل أسبوع تُرسل نتائجك، ومتخصصك يعدّل خطتك", en: "Each week you send your results, your specialist adjusts your plan" } }
    ]
  },
  login: {
    title: { ar: "دخول الموظفين", en: "Staff Login" },
    hint: { ar: "أدخل رمز الدخول الخاص بك. (admin123 للمدير، spec123 للمتخصص)", en: "Enter your access code. (admin123 for admin, spec123 for specialist)" },
    loginBtn: { ar: "تسجيل الدخول", en: "Login" },
    back: { ar: "العودة كعميل", en: "Back as Customer" },
    error: { ar: "رمز الدخول غير صحيح!", en: "Invalid access code!" }
  },
  quiz: {
    question: { ar: "السؤال", en: "Question" },
    of: { ar: "من", en: "of" },
    optional: { ar: "اختياري", en: "Optional" },
    back: { ar: "← رجوع", en: "← Back" },
    next: { ar: "التالي ←", en: "Next →" },
    generate: { ar: "🚀 أنشئ خطتي بالذكاء الاصطناعي", en: "🚀 Generate My AI Plan" },
    phoneHint: { ar: "يرجى إدخال رقم هاتف صحيح", en: "Please enter a valid phone number" },
    multiHint: { ar: "يمكنك اختيار أكثر من إجابة", en: "You can select multiple answers" },
    healthNoteTitle: { ar: "📝 تفاصيل إضافية عن وضعك الصحي", en: "📝 Additional Health Details" },
    healthNoteSent: { ar: "✓ ستُرسل هذه المعلومات إلى المتخصص مباشرة", en: "✓ This information will be sent directly to the specialist" },
    healthyWeight: { ar: "الوزن الصحي المثالي حسب طولك", en: "Healthy Ideal Weight for Your Height" },
    healthyRange: { ar: "النطاق الصحي", en: "Healthy Range" },
    customTarget: { ar: "أختار هدفي بنفسي", en: "Choose My Own Goal" },
    currentStatus: { ar: "وضعك الحالي", en: "Your Current Status" },
    bmi: { ar: "مؤشر كتلة الجسم", en: "Body Mass Index" },
    popularCountries: { ar: "الأكثر شيوعاً", en: "Most Popular" },
    noResults: { ar: "لا توجد نتائج — جرّب كتابة مختلفة", en: "No results — Try a different search" }
  },
  generating: {
    title: { ar: "متخصصنا يبني خطتك...", en: "Our Specialist is Building Your Plan..." },
    time: { ar: "يستغرق عادةً من 15 إلى 30 ثانية", en: "Usually takes 15 to 30 seconds" }
  },
  error: {
    rateLimit: { ar: "الخدمة مشغولة مؤقتاً", en: "Service Temporarily Busy" },
    rateLimitDesc: { ar: "وصلنا للحد الأقصى للاستخدام. انتظر بضع دقائق وحاول مجدداً.", en: "Usage limit reached. Wait a few minutes and try again." },
    general: { ar: "تعذّر توليد الخطة", en: "Failed to Generate Plan" },
    generalDesc: { ar: "حدث خطأ أثناء التوليد. تحقق من اتصالك بالإنترنت وحاول مجدداً.", en: "An error occurred during generation. Check your internet connection and try again." },
    details: { ar: "تفاصيل الخطأ", en: "Error Details" },
    retry: { ar: "حاول مجدداً ←", en: "Try Again →" },
    restart: { ar: "البداية من جديد", en: "Start Over" }
  },
  plan: {
    pending: { ar: "⏳ بانتظار موافقة المتخصص", en: "⏳ Awaiting Specialist Approval" },
    ready: { ar: "✦ خطتك جاهزة وقيد المراجعة", en: "✦ Your Plan is Ready and Under Review" },
    hello: { ar: "مرحباً", en: "Hello" },
    contact: { ar: "سيتواصل معك المتخصص قريباً", en: "Specialist will contact you soon" },
    level: { ar: "المستوى", en: "Level" },
    points: { ar: "نقطة (XP)", en: "Points (XP)" },
    streak: { ar: "شعلة الالتزام", en: "Commitment Streak" },
    calories: { ar: "سعرة / يوم", en: "cal/day" },
    goal: { ar: "الهدف المقرر", en: "Target Goal" },
    protein: { ar: "بروتين", en: "Protein" },
    carbs: { ar: "كربوهيدرات", en: "Carbs" },
    fats: { ar: "دهون", en: "Fats" },
    weeklyPlan: { ar: "📅 الخطة الأسبوعية", en: "📅 Weekly Plan" },
    preview: { ar: "— معاينة مجانية ليوم واحد 🔒", en: "— Free Preview for One Day 🔒" },
    breakfast: { ar: "🌅 الفطور", en: "🌅 Breakfast" },
    lunch: { ar: "☀️ الغداء", en: "☀️ Lunch" },
    dinner: { ar: "🌙 العشاء", en: "🌙 Dinner" },
    snack: { ar: "🍎 وجبة خفيفة", en: "🍎 Snack" },
    chooseOne: { ar: "اختر بديلاً واحداً فقط لكل وجبة", en: "Choose only one alternative per meal" },
    or: { ar: "أو", en: "Or" },
    locked: { ar: "🔒 باقي المحتوى مقفول", en: "🔒 Remaining content locked" },
    lockedDesc: { ar: "ادفع الآن لفتح جميع الوجبات، التمارين المفصلة، والنصائح الكاملة.", en: "Pay now to unlock all meals, detailed workouts, and full tips." },
    workout: { ar: "🏋️ روتين رياضي منزلي", en: "🏋️ Home Workout Routine" },
    tips: { ar: "💡 نصائح مخصصة لك", en: "💡 Personalized Tips" },
    payment: { ar: "💳 إتمام الاشتراك", en: "💳 Complete Subscription" },
    paymentDesc: { ar: "خطتك جاهزة وتمت مراجعتها. جرّب الأسبوع الأول — إن أحسست بفرق حقيقي، استمر.", en: "Your plan is ready and reviewed. Try the first week — if you feel a real difference, continue." },
    weekFee: { ar: "رسوم الأسبوع", en: "Week Fee" },
    payWeekly: { ar: "يُدفع أسبوعاً بعد أسبوع فقط", en: "Paid weekly only" },
    paid: { ar: "✅ تم الدفع بنجاح — تم تفعيل الخطة كاملة!", en: "✅ Payment Successful — Full Plan Activated!" },
    receipt: { ar: "رقم الإيصال", en: "Receipt Number" },
    sending: { ar: "جاري إرسال الخطة الأسبوعية عبر واتساب...", en: "Sending weekly plan via WhatsApp..." },
    sent: { ar: "📱 تم إرسال الخطة بنجاح إلى رقمك!", en: "📱 Plan sent successfully to your number!" },
    payBtn: { ar: "ادفع الآن عبر PayPal", en: "Pay Now via PayPal" },
    paying: { ar: "جارٍ تأكيد الدفع...", en: "Confirming payment..." },
    secure: { ar: "🔒 دفع آمن عبر PayPal · لا تُحفظ بيانات بطاقتك", en: "🔒 Secure PayPal payment · Your card details are not stored" },
    specialistPanel: { ar: "⚕️ لوحة المتخصص", en: "⚕️ Specialist Panel" },
    admin: { ar: "(مدير)", en: "(Admin)" },
    medicalNotes: { ar: "📝 ملاحظات طبية — للمتخصص فقط", en: "📝 Medical Notes — For Specialist Only" },
    patientNotes: { ar: "📝 ملاحظات المريض بكلامه", en: "📝 Patient Notes in Their Own Words" },
    approve: { ar: "✅ اعتماد الخطة والموافقة عليها", en: "✅ Approve and Confirm Plan" },
    approved: { ar: "✓ تمت الموافقة على الخطة", en: "✓ Plan Approved" },
    backend: { ar: "🔄 تتبع النظام الآلي (Backend Status)", en: "🔄 Backend Status Tracking" },
    paymentStatus: { ar: "حالة الدفع", en: "Payment Status" },
    paidStatus: { ar: "تم الدفع بنجاح", en: "Payment Successful" },
    waitingPayment: { ar: "بانتظار الدفع...", en: "Awaiting Payment..." },
    whatsappStatus: { ar: "إرسال واتساب", en: "WhatsApp Sending" },
    whatsappSentStatus: { ar: "تم الإرسال آلياً عبر Cloud API", en: "Sent automatically via Cloud API" },
    dailyFollowup: { ar: "🔔 متابعة يومية (واتساب - يدوية مؤقتاً)", en: "🔔 Daily Follow-up (WhatsApp - Manual for now)" },
    followupNote: { ar: "سيتم ربطها آلياً عبر Firebase Functions لاحقاً", en: "Will be automated via Firebase Functions later" },
    morningMsg: { ar: "🌅 رسالة الصباح الترحيبية", en: "🌅 Morning Welcome Message" },
    middayMsg: { ar: "☀️ متابعة منتصف اليوم", en: "☀️ Midday Follow-up" },
    eveningMsg: { ar: "🌙 رسالة المساء التحفيزية", en: "🌙 Evening Motivational Message" },
    followupWeek: { ar: "📅 هل مرّ أسبوع على البرنامج؟", en: "📅 Has a Week Passed?" },
    followupDesc: { ar: "أرسل لي نتائجك وسأعدّل خطتك للأسبوع القادم بناءً على تقدمك الفعلي", en: "Send me your results and I'll adjust your plan for next week based on your actual progress" },
    followupBtn: { ar: "متابعة الأسبوع", en: "Follow-up Week" },
    restart: { ar: "← البداية من جديد", en: "← Start Over" },
    your_info: { ar: "📋 معلوماتك", en: "📋 Your Info" },
    age: { ar: "العمر", en: "Age" },
    gender: { ar: "الجنس", en: "Gender" },
    height: { ar: "الطول", en: "Height" },
    weight: { ar: "الوزن", en: "Weight" },
    target: { ar: "الهدف", en: "Target" },
    bmi: { ar: "مؤشر كتلة الجسم", en: "BMI" },
    conditions: { ar: "حالات صحية", en: "Conditions" },
    allergies: { ar: "حساسيات", en: "Allergies" },
    activity: { ar: "نشاط بدني", en: "Activity" },
    food_pref: { ar: "تفضيلات طعام", en: "Food Preferences" },
    country: { ar: "البلد", en: "Country" }
  },
  followup: {
    title: { ar: "متابعة الأسبوع", en: "Week Follow-up" },
    questions: [
      { id: "new_weight", icon: "⚖️", title: { ar: "كم وزنك اليوم؟", en: "What's your weight today?" }, sub: { ar: "قِسه الآن قبل الإجابة للدقة", en: "Measure it now before answering for accuracy" }, type: "number", unit: { ar: "كجم", en: "kg" }, required: true },
      { id: "adherence", icon: "📋", title: { ar: "كم يوماً التزمت بالخطة الغذائية؟", en: "How many days did you stick to the plan?" }, sub: { ar: "كن صادقاً — هذا يساعدني في تعديل خطتك", en: "Be honest — this helps me adjust your plan" }, type: "choice", options: { ar: ["7 أيام كاملة 🏆", "5 إلى 6 أيام ✅", "3 إلى 4 أيام 😐", "يوم أو يومان 😕", "لم أستطع الالتزام 😞"], en: ["7 Full Days 🏆", "5-6 Days ✅", "3-4 Days 😐", "1-2 Days 😕", "Couldn't Commit 😞"] }, required: true },
      { id: "hard_meals", icon: "🍽️", title: { ar: "أي وجبة كانت الأصعب في التطبيق؟", en: "Which meal was hardest to follow?" }, sub: { ar: "سأغيّرها لك في الأسبوع القادم", en: "I'll change it for you next week" }, type: "choice", options: { ar: ["الفطور", "الغداء", "العشاء", "الوجبة الخفيفة", "لم تكن هناك صعوبة"], en: ["Breakfast", "Lunch", "Dinner", "Snack", "No Difficulty"] }, required: true },
      { id: "energy", icon: "⚡", title: { ar: "كيف كان مستوى طاقتك خلال الأسبوع؟", en: "How was your energy level this week?" }, sub: { ar: "الطاقة المنخفضة تعني أن السعرات تحتاج تعديلاً", en: "Low energy means calories need adjustment" }, type: "choice", options: { ar: ["ممتاز — نشيط طوال الوقت 💪", "جيد — بشكل عام مقبول 😊", "متذبذب — أحياناً تعب 😐", "منخفض — تعبت كثيراً 😔", "منهك جداً 🔴"], en: ["Excellent — Energetic All Day 💪", "Good — Generally Okay 😊", "Fluctuating — Sometimes Tired 😐", "Low — Very Tired 😔", "Exhausted 🔴"] }, required: true },
      { id: "side_effects", icon: "🩺", title: { ar: "هل لاحظت أي أعراض جسدية هذا الأسبوع؟", en: "Did you notice any physical symptoms this week?" }, sub: { ar: "أي شيء غير معتاد يهمني أن أعرفه", en: "Anything unusual, I need to know" }, type: "multichoice", options: { ar: ["لا شيء — كل شيء طبيعي ✅", "صداع متكرر", "دوخة أو إغماء", "إمساك أو اضطراب هضمي", "نوم مضطرب", "جوع شديد", "آخر"], en: ["Nothing — All Normal ✅", "Frequent Headaches", "Dizziness or Fainting", "Constipation or Digestive Issues", "Disturbed Sleep", "Extreme Hunger", "Other"] }, required: true },
      { id: "notes", icon: "💬", title: { ar: "هل ثمة شيء تريد إخباري به؟", en: "Is there anything you want to tell me?" }, sub: { ar: "أي ملاحظة أو تغيير في حياتك أو صحتك هذا الأسبوع", en: "Any notes or changes in your life or health this week" }, type: "textarea", required: false }
    ],
    progress: { ar: "السؤال", en: "Question" },
    generateBtn: { ar: "🚀 أنشئ خطة الأسبوع الجديد", en: "🚀 Generate New Week Plan" }
  },
  community: {
    title: { ar: "🌍 المجتمع", en: "🌍 Community" },
    leaderboard: { ar: "🏆 المتصدرون", en: "🏆 Leaderboard" },
    follow: { ar: "متابعة", en: "Follow" },
    unfollow: { ar: "إلغاء المتابعة", en: "Unfollow" },
    posts: { ar: "📸 منشورات التحول", en: "📸 Transformations" },
    postPlaceholder: { ar: "اكتب تعليقاً عن تقدمك...", en: "Write a comment about your progress..." },
    uploadPhoto: { ar: "📷 أضف صورة", en: "📷 Add Photo" },
    publish: { ar: "نشر", en: "Publish" },
    beforeAfter: { ar: "قبل / بعد", en: "Before / After" }
  },
  profile: {
    title: { ar: "الملف الشخصي", en: "Profile" },
    xp: { ar: "نقاط الخبرة", en: "XP" },
    streak: { ar: "الشعلة", en: "Streak" },
    level: { ar: "المستوى", en: "Level" },
    badges: { ar: "شارات", en: "Badges" }
  },
  questions: [
    { id: "first_name", type: "text", label: { ar: "اسمك الأول؟", en: "Your first name?" }, placeholder: { ar: "أدخل اسمك", en: "Enter your name" }, icon: "👤", required: true },
    { id: "email", type: "email", required: true, label: { ar: "البريد الإلكتروني", en: "Email address" }, placeholder: { ar: "example@domain.com", en: "example@domain.com" }, icon: "📧" },
    { id: "phone", type: "tel", label: { ar: "رقم هاتفك (اختياري)", en: "Phone number (optional)" }, placeholder: { ar: "مثال: 0096599001234", en: "Example: 0096599001234" }, icon: "📱", required: false, hint: { ar: "لن نزعجك، فقط للمتابعة الأسبوعية", en: "We'll only use it for weekly follow-up" } },
    { id: "age", type: "number", label: { ar: "كم عمرك؟", en: "How old are you?" }, placeholder: { ar: "مثال: 30", en: "Example: 30" }, unit: { ar: "سنة", en: "years" }, icon: "🎂", required: true },
    { id: "gender", type: "choice", label: { ar: "الجنس", en: "Gender" }, options: { ar: ["ذكر", "أنثى"], en: ["Male", "Female"] }, icon: "⚧", required: true },
    { id: "height", type: "number", label: { ar: "طولك (سم)", en: "Your height (cm)" }, placeholder: { ar: "مثال: 170", en: "Example: 170" }, unit: { ar: "سم", en: "cm" }, icon: "📏", required: true },
    { id: "current_weight", type: "number", label: { ar: "وزنك الحالي (كجم)", en: "Current weight (kg)" }, placeholder: { ar: "مثال: 90", en: "Example: 90" }, unit: { ar: "كجم", en: "kg" }, icon: "⚖️", required: true },
    { id: "target_weight", type: "smart_target", label: { ar: "الوزن المستهدف", en: "Target weight" }, icon: "🎯", required: true },
    {
      id: "health_conditions", type: "multichoice_notes",
      label: { ar: "أمراض مزمنة أو أدوية؟", en: "Chronic diseases or medications?" },
      options: { ar: ["لا يوجد", "سكري", "ضغط", "قلب", "غدة", "كلى", "كبد", "أخرى"], en: ["None", "Diabetes", "Hypertension", "Heart", "Thyroid", "Kidney", "Liver", "Other"] },
      icon: "🏥", required: true,
      warn: { ar: "هذه المعلومات ضرورية لسلامتك", en: "This info is essential for your safety" },
      notePlaceholder: { ar: "اكتب الأمراض والأدوية بالتفصيل...", en: "List any diseases & medications..." }
    },
    {
      id: "allergies", type: "multichoice_notes",
      label: { ar: "حساسية أو أطعمة ممنوعة؟", en: "Allergies / forbidden foods?" },
      options: { ar: ["لا يوجد", "لاكتوز", "جلوتين", "مكسرات", "بيض", "بحريات", "أخرى"], en: ["None", "Lactose", "Gluten", "Nuts", "Eggs", "Seafood", "Other"] },
      icon: "⚠️",
      notePlaceholder: { ar: "أي أطعمة لا تتحملها؟", en: "Any foods you can't eat?" }
    },
    {
      id: "activity", type: "choice",
      label: { ar: "مستوى نشاطك البدني", en: "Physical activity level" },
      options: { ar: ["لا أمارس رياضة", "خفيف (مرة بالأسبوع)", "متوسط (3 مرات)", "عالي (يوميًا)"], en: ["Sedentary (no exercise)", "Light (1x/week)", "Moderate (3x/week)", "Active (daily)"] },
      icon: "🏃"
    },
    {
      id: "food_pref", type: "multichoice",
      label: { ar: "تفضيلاتك الغذائية", en: "Your food preferences" },
      options: { ar: ["آكل كل شيء", "نباتي", "دجاج وسمك فقط", "لحوم حمراء", "لا أحب الخضروات"], en: ["Eat everything", "Vegetarian", "Chicken & Fish only", "Red meat", "Don't like vegetables"] },
      icon: "🥗"
    },
    // ========== 5 NEW OPTIONAL HEALTH QUESTIONS ==========
    {
      id: "sleep_hours",
      type: "number",
      label: { ar: "كم ساعة تنام في الليلة؟ (اختياري)", en: "How many hours do you sleep per night? (optional)" },
      placeholder: { ar: "مثال: 7", en: "Example: 7" },
      unit: { ar: "ساعات", en: "hours" },
      icon: "😴",
      required: false,
      hint: { ar: "النوم الجيد يساعد في التحكم بالشهية", en: "Good sleep helps control appetite" }
    },
    {
      id: "smoking",
      type: "choice",
      label: { ar: "هل تدخن أو تستخدم الفيب؟ (اختياري)", en: "Do you smoke or vape? (optional)" },
      options: { ar: ["لا", "نعم - سجائر", "نعم - فيب", "نعم - شيشة"], en: ["No", "Yes - cigarettes", "Yes - vape", "Yes - hookah"] },
      icon: "🚬",
      required: false
    },
    {
      id: "stress_level",
      type: "choice",
      label: { ar: "مستوى التوتر اليومي (اختياري)", en: "Daily stress level (optional)" },
      options: { ar: ["منخفض (1-3)", "متوسط (4-6)", "مرتفع (7-8)", "شديد جداً (9-10)"], en: ["Low (1-3)", "Moderate (4-6)", "High (7-8)", "Very high (9-10)"] },
      icon: "😰",
      required: false,
      hint: { ar: "التوتر يؤثر على الرغبة في تناول السكريات", en: "Stress affects sugar cravings" }
    },
    {
      id: "cooking_time",
      type: "choice",
      label: { ar: "الوقت المتاح لك للطهي يومياً (اختياري)", en: "Time available for cooking daily (optional)" },
      options: { ar: ["أقل من 15 دقيقة", "15-30 دقيقة", "30-60 دقيقة", "أكثر من ساعة"], en: ["Less than 15 min", "15-30 min", "30-60 min", "More than 1 hour"] },
      icon: "⏲️",
      required: false
    },
    {
      id: "previous_surgeries",
      type: "textarea",
      label: { ar: "هل خضعت لعمليات جراحية سابقة (خاصة المعدة أو الأمعاء)؟ (اختياري)", en: "Have you had any previous surgeries (especially stomach or intestines)? (optional)" },
      placeholder: { ar: "اذكر العملية وتاريخها إن أمكن...", en: "Mention the surgery and date if possible..." },
      icon: "🏥",
      required: false,
      hint: { ar: "بعض العمليات تؤثر على امتصاص الغذاء", en: "Some surgeries affect nutrient absorption" }
    },
    // End of new questions
    { id: "country", type: "country_search", label: { ar: "دولة إقامتك", en: "Your country" }, placeholder: { ar: "ابحث عن دولتك...", en: "Search your country..." }, icon: "🌍", required: true },
  ],
  common: {
    loading: { ar: "جارٍ تحليل بياناتك...", en: "Analyzing your data..." },
    loading2: { ar: "متخصصنا يدرس ملفك الصحي...", en: "Our specialist is reviewing your health file..." },
    loading3: { ar: "تخصيص الوجبات حسب جسمك وبلدك...", en: "Customizing meals for your body and country..." },
    loading4: { ar: "حساب السعرات الحرارية المثالية...", en: "Calculating ideal calories..." },
    loading5: { ar: "مراجعة الخطة الغذائية...", en: "Reviewing nutrition plan..." },
    loading6: { ar: "اللمسات الأخيرة قبل إرسالها...", en: "Final touches before sending..." },
  }
};

// Full countries list (Palestine included, Israel excluded)
export const COUNTRIES = [
  // Africa
  { nameAr: "مصر", nameEn: "Egypt", flag: "https://flagcdn.com/w40/eg.png" },
  { nameAr: "الجزائر", nameEn: "Algeria", flag: "https://flagcdn.com/w40/dz.png" },
  { nameAr: "المغرب", nameEn: "Morocco", flag: "https://flagcdn.com/w40/ma.png" },
  { nameAr: "تونس", nameEn: "Tunisia", flag: "https://flagcdn.com/w40/tn.png" },
  { nameAr: "ليبيا", nameEn: "Libya", flag: "https://flagcdn.com/w40/ly.png" },
  { nameAr: "السودان", nameEn: "Sudan", flag: "https://flagcdn.com/w40/sd.png" },
  { nameAr: "جنوب السودان", nameEn: "South Sudan", flag: "https://flagcdn.com/w40/ss.png" },
  { nameAr: "إريتريا", nameEn: "Eritrea", flag: "https://flagcdn.com/w40/er.png" },
  { nameAr: "جيبوتي", nameEn: "Djibouti", flag: "https://flagcdn.com/w40/dj.png" },
  { nameAr: "الصومال", nameEn: "Somalia", flag: "https://flagcdn.com/w40/so.png" },
  { nameAr: "جزر القمر", nameEn: "Comoros", flag: "https://flagcdn.com/w40/km.png" },
  { nameAr: "موريتانيا", nameEn: "Mauritania", flag: "https://flagcdn.com/w40/mr.png" },
  { nameAr: "السنغال", nameEn: "Senegal", flag: "https://flagcdn.com/w40/sn.png" },
  { nameAr: "غامبيا", nameEn: "Gambia", flag: "https://flagcdn.com/w40/gm.png" },
  { nameAr: "غينيا", nameEn: "Guinea", flag: "https://flagcdn.com/w40/gn.png" },
  { nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau", flag: "https://flagcdn.com/w40/gw.png" },
  { nameAr: "غينيا الاستوائية", nameEn: "Equatorial Guinea", flag: "https://flagcdn.com/w40/gq.png" },
  { nameAr: "سيراليون", nameEn: "Sierra Leone", flag: "https://flagcdn.com/w40/sl.png" },
  { nameAr: "ليبيريا", nameEn: "Liberia", flag: "https://flagcdn.com/w40/lr.png" },
  { nameAr: "ساحل العاج", nameEn: "Ivory Coast", flag: "https://flagcdn.com/w40/ci.png" },
  { nameAr: "غانا", nameEn: "Ghana", flag: "https://flagcdn.com/w40/gh.png" },
  { nameAr: "توغو", nameEn: "Togo", flag: "https://flagcdn.com/w40/tg.png" },
  { nameAr: "بنين", nameEn: "Benin", flag: "https://flagcdn.com/w40/bj.png" },
  { nameAr: "بوركينا فاسو", nameEn: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png" },
  { nameAr: "مالي", nameEn: "Mali", flag: "https://flagcdn.com/w40/ml.png" },
  { nameAr: "النيجر", nameEn: "Niger", flag: "https://flagcdn.com/w40/ne.png" },
  { nameAr: "تشاد", nameEn: "Chad", flag: "https://flagcdn.com/w40/td.png" },
  { nameAr: "نيجيريا", nameEn: "Nigeria", flag: "https://flagcdn.com/w40/ng.png" },
  { nameAr: "الكاميرون", nameEn: "Cameroon", flag: "https://flagcdn.com/w40/cm.png" },
  { nameAr: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic", flag: "https://flagcdn.com/w40/cf.png" },
  { nameAr: "الكونغو", nameEn: "Congo", flag: "https://flagcdn.com/w40/cg.png" },
  { nameAr: "الكونغو الديمقراطية", nameEn: "DR Congo", flag: "https://flagcdn.com/w40/cd.png" },
  { nameAr: "رواندا", nameEn: "Rwanda", flag: "https://flagcdn.com/w40/rw.png" },
  { nameAr: "بوروندي", nameEn: "Burundi", flag: "https://flagcdn.com/w40/bi.png" },
  { nameAr: "أوغندا", nameEn: "Uganda", flag: "https://flagcdn.com/w40/ug.png" },
  { nameAr: "كينيا", nameEn: "Kenya", flag: "https://flagcdn.com/w40/ke.png" },
  { nameAr: "تنزانيا", nameEn: "Tanzania", flag: "https://flagcdn.com/w40/tz.png" },
  { nameAr: "موزمبيق", nameEn: "Mozambique", flag: "https://flagcdn.com/w40/mz.png" },
  { nameAr: "مالاوي", nameEn: "Malawi", flag: "https://flagcdn.com/w40/mw.png" },
  { nameAr: "زامبيا", nameEn: "Zambia", flag: "https://flagcdn.com/w40/zm.png" },
  { nameAr: "زيمبابوي", nameEn: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png" },
  { nameAr: "بوتسوانا", nameEn: "Botswana", flag: "https://flagcdn.com/w40/bw.png" },
  { nameAr: "ناميبيا", nameEn: "Namibia", flag: "https://flagcdn.com/w40/na.png" },
  { nameAr: "جنوب أفريقيا", nameEn: "South Africa", flag: "https://flagcdn.com/w40/za.png" },
  { nameAr: "إسواتيني", nameEn: "Eswatini", flag: "https://flagcdn.com/w40/sz.png" },
  { nameAr: "ليسوتو", nameEn: "Lesotho", flag: "https://flagcdn.com/w40/ls.png" },
  { nameAr: "مدغشقر", nameEn: "Madagascar", flag: "https://flagcdn.com/w40/mg.png" },
  { nameAr: "سيشل", nameEn: "Seychelles", flag: "https://flagcdn.com/w40/sc.png" },
  { nameAr: "موريشيوس", nameEn: "Mauritius", flag: "https://flagcdn.com/w40/mu.png" },
  { nameAr: "الرأس الأخضر", nameEn: "Cape Verde", flag: "https://flagcdn.com/w40/cv.png" },
  { nameAr: "ساو تومي وبرينسيب", nameEn: "Sao Tome and Principe", flag: "https://flagcdn.com/w40/st.png" },
  { nameAr: "أنغولا", nameEn: "Angola", flag: "https://flagcdn.com/w40/ao.png" },

  // Asia (including Palestine, excluding Israel)
  { nameAr: "السعودية", nameEn: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png" },
  { nameAr: "الكويت", nameEn: "Kuwait", flag: "https://flagcdn.com/w40/kw.png" },
  { nameAr: "الإمارات", nameEn: "United Arab Emirates", flag: "https://flagcdn.com/w40/ae.png" },
  { nameAr: "قطر", nameEn: "Qatar", flag: "https://flagcdn.com/w40/qa.png" },
  { nameAr: "البحرين", nameEn: "Bahrain", flag: "https://flagcdn.com/w40/bh.png" },
  { nameAr: "عمان", nameEn: "Oman", flag: "https://flagcdn.com/w40/om.png" },
  { nameAr: "اليمن", nameEn: "Yemen", flag: "https://flagcdn.com/w40/ye.png" },
  { nameAr: "الأردن", nameEn: "Jordan", flag: "https://flagcdn.com/w40/jo.png" },
  { nameAr: "لبنان", nameEn: "Lebanon", flag: "https://flagcdn.com/w40/lb.png" },
  { nameAr: "سوريا", nameEn: "Syria", flag: "https://flagcdn.com/w40/sy.png" },
  { nameAr: "العراق", nameEn: "Iraq", flag: "https://flagcdn.com/w40/iq.png" },
  { nameAr: "فلسطين", nameEn: "Palestine", flag: "https://flagcdn.com/w40/ps.png" },
  { nameAr: "تركيا", nameEn: "Turkey", flag: "https://flagcdn.com/w40/tr.png" },
  { nameAr: "إيران", nameEn: "Iran", flag: "https://flagcdn.com/w40/ir.png" },
  { nameAr: "أفغانستان", nameEn: "Afghanistan", flag: "https://flagcdn.com/w40/af.png" },
  { nameAr: "باكستان", nameEn: "Pakistan", flag: "https://flagcdn.com/w40/pk.png" },
  { nameAr: "الهند", nameEn: "India", flag: "https://flagcdn.com/w40/in.png" },
  { nameAr: "نيبال", nameEn: "Nepal", flag: "https://flagcdn.com/w40/np.png" },
  { nameAr: "بوتان", nameEn: "Bhutan", flag: "https://flagcdn.com/w40/bt.png" },
  { nameAr: "بنغلاديش", nameEn: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png" },
  { nameAr: "ميانمار", nameEn: "Myanmar", flag: "https://flagcdn.com/w40/mm.png" },
  { nameAr: "الصين", nameEn: "China", flag: "https://flagcdn.com/w40/cn.png" },
  { nameAr: "تايوان", nameEn: "Taiwan", flag: "https://flagcdn.com/w40/tw.png" },
  { nameAr: "منغوليا", nameEn: "Mongolia", flag: "https://flagcdn.com/w40/mn.png" },
  { nameAr: "كوريا الشمالية", nameEn: "North Korea", flag: "https://flagcdn.com/w40/kp.png" },
  { nameAr: "كوريا الجنوبية", nameEn: "South Korea", flag: "https://flagcdn.com/w40/kr.png" },
  { nameAr: "اليابان", nameEn: "Japan", flag: "https://flagcdn.com/w40/jp.png" },
  { nameAr: "فيتنام", nameEn: "Vietnam", flag: "https://flagcdn.com/w40/vn.png" },
  { nameAr: "لاوس", nameEn: "Laos", flag: "https://flagcdn.com/w40/la.png" },
  { nameAr: "كمبوديا", nameEn: "Cambodia", flag: "https://flagcdn.com/w40/kh.png" },
  { nameAr: "تايلاند", nameEn: "Thailand", flag: "https://flagcdn.com/w40/th.png" },
  { nameAr: "ماليزيا", nameEn: "Malaysia", flag: "https://flagcdn.com/w40/my.png" },
  { nameAr: "سنغافورة", nameEn: "Singapore", flag: "https://flagcdn.com/w40/sg.png" },
  { nameAr: "إندونيسيا", nameEn: "Indonesia", flag: "https://flagcdn.com/w40/id.png" },
  { nameAr: "الفلبين", nameEn: "Philippines", flag: "https://flagcdn.com/w40/ph.png" },
  { nameAr: "بروناي", nameEn: "Brunei", flag: "https://flagcdn.com/w40/bn.png" },
  { nameAr: "تيمور الشرقية", nameEn: "East Timor", flag: "https://flagcdn.com/w40/tl.png" },
  { nameAr: "سريلانكا", nameEn: "Sri Lanka", flag: "https://flagcdn.com/w40/lk.png" },
  { nameAr: "جزر المالديف", nameEn: "Maldives", flag: "https://flagcdn.com/w40/mv.png" },
  { nameAr: "كازاخستان", nameEn: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png" },
  { nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan", flag: "https://flagcdn.com/w40/kg.png" },
  { nameAr: "طاجيكستان", nameEn: "Tajikistan", flag: "https://flagcdn.com/w40/tj.png" },
  { nameAr: "أوزبكستان", nameEn: "Uzbekistan", flag: "https://flagcdn.com/w40/uz.png" },
  { nameAr: "تركمانستان", nameEn: "Turkmenistan", flag: "https://flagcdn.com/w40/tm.png" },
  { nameAr: "أذربيجان", nameEn: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png" },
  { nameAr: "جورجيا", nameEn: "Georgia", flag: "https://flagcdn.com/w40/ge.png" },
  { nameAr: "أرمينيا", nameEn: "Armenia", flag: "https://flagcdn.com/w40/am.png" },

  // Europe
  { nameAr: "روسيا", nameEn: "Russia", flag: "https://flagcdn.com/w40/ru.png" },
  { nameAr: "أوكرانيا", nameEn: "Ukraine", flag: "https://flagcdn.com/w40/ua.png" },
  { nameAr: "بيلاروسيا", nameEn: "Belarus", flag: "https://flagcdn.com/w40/by.png" },
  { nameAr: "بولندا", nameEn: "Poland", flag: "https://flagcdn.com/w40/pl.png" },
  { nameAr: "التشيك", nameEn: "Czech Republic", flag: "https://flagcdn.com/w40/cz.png" },
  { nameAr: "سلوفاكيا", nameEn: "Slovakia", flag: "https://flagcdn.com/w40/sk.png" },
  { nameAr: "المجر", nameEn: "Hungary", flag: "https://flagcdn.com/w40/hu.png" },
  { nameAr: "رومانيا", nameEn: "Romania", flag: "https://flagcdn.com/w40/ro.png" },
  { nameAr: "بلغاريا", nameEn: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png" },
  { nameAr: "مولدوفا", nameEn: "Moldova", flag: "https://flagcdn.com/w40/md.png" },
  { nameAr: "صربيا", nameEn: "Serbia", flag: "https://flagcdn.com/w40/rs.png" },
  { nameAr: "الجبل الأسود", nameEn: "Montenegro", flag: "https://flagcdn.com/w40/me.png" },
  { nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w40/ba.png" },
  { nameAr: "كرواتيا", nameEn: "Croatia", flag: "https://flagcdn.com/w40/hr.png" },
  { nameAr: "سلوفينيا", nameEn: "Slovenia", flag: "https://flagcdn.com/w40/si.png" },
  { nameAr: "ألبانيا", nameEn: "Albania", flag: "https://flagcdn.com/w40/al.png" },
  { nameAr: "مقدونيا الشمالية", nameEn: "North Macedonia", flag: "https://flagcdn.com/w40/mk.png" },
  { nameAr: "اليونان", nameEn: "Greece", flag: "https://flagcdn.com/w40/gr.png" },
  { nameAr: "قبرص", nameEn: "Cyprus", flag: "https://flagcdn.com/w40/cy.png" },
  { nameAr: "مالطا", nameEn: "Malta", flag: "https://flagcdn.com/w40/mt.png" },
  { nameAr: "إيطاليا", nameEn: "Italy", flag: "https://flagcdn.com/w40/it.png" },
  { nameAr: "إسبانيا", nameEn: "Spain", flag: "https://flagcdn.com/w40/es.png" },
  { nameAr: "البرتغال", nameEn: "Portugal", flag: "https://flagcdn.com/w40/pt.png" },
  { nameAr: "فرنسا", nameEn: "France", flag: "https://flagcdn.com/w40/fr.png" },
  { nameAr: "بلجيكا", nameEn: "Belgium", flag: "https://flagcdn.com/w40/be.png" },
  { nameAr: "هولندا", nameEn: "Netherlands", flag: "https://flagcdn.com/w40/nl.png" },
  { nameAr: "لوكسمبورغ", nameEn: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png" },
  { nameAr: "ألمانيا", nameEn: "Germany", flag: "https://flagcdn.com/w40/de.png" },
  { nameAr: "سويسرا", nameEn: "Switzerland", flag: "https://flagcdn.com/w40/ch.png" },
  { nameAr: "النمسا", nameEn: "Austria", flag: "https://flagcdn.com/w40/at.png" },
  { nameAr: "ليختنشتاين", nameEn: "Liechtenstein", flag: "https://flagcdn.com/w40/li.png" },
  { nameAr: "المملكة المتحدة", nameEn: "United Kingdom", flag: "https://flagcdn.com/w40/gb.png" },
  { nameAr: "أيرلندا", nameEn: "Ireland", flag: "https://flagcdn.com/w40/ie.png" },
  { nameAr: "آيسلندا", nameEn: "Iceland", flag: "https://flagcdn.com/w40/is.png" },
  { nameAr: "الدنمارك", nameEn: "Denmark", flag: "https://flagcdn.com/w40/dk.png" },
  { nameAr: "النرويج", nameEn: "Norway", flag: "https://flagcdn.com/w40/no.png" },
  { nameAr: "السويد", nameEn: "Sweden", flag: "https://flagcdn.com/w40/se.png" },
  { nameAr: "فنلندا", nameEn: "Finland", flag: "https://flagcdn.com/w40/fi.png" },
  { nameAr: "إستونيا", nameEn: "Estonia", flag: "https://flagcdn.com/w40/ee.png" },
  { nameAr: "لاتفيا", nameEn: "Latvia", flag: "https://flagcdn.com/w40/lv.png" },
  { nameAr: "ليتوانيا", nameEn: "Lithuania", flag: "https://flagcdn.com/w40/lt.png" },
  { nameAr: "موناكو", nameEn: "Monaco", flag: "https://flagcdn.com/w40/mc.png" },
  { nameAr: "أندورا", nameEn: "Andorra", flag: "https://flagcdn.com/w40/ad.png" },
  { nameAr: "سان مارينو", nameEn: "San Marino", flag: "https://flagcdn.com/w40/sm.png" },
  { nameAr: "الفاتيكان", nameEn: "Vatican City", flag: "https://flagcdn.com/w40/va.png" },

  // Americas
  { nameAr: "كندا", nameEn: "Canada", flag: "https://flagcdn.com/w40/ca.png" },
  { nameAr: "الولايات المتحدة", nameEn: "United States", flag: "https://flagcdn.com/w40/us.png" },
  { nameAr: "المكسيك", nameEn: "Mexico", flag: "https://flagcdn.com/w40/mx.png" },
  { nameAr: "غواتيمالا", nameEn: "Guatemala", flag: "https://flagcdn.com/w40/gt.png" },
  { nameAr: "بليز", nameEn: "Belize", flag: "https://flagcdn.com/w40/bz.png" },
  { nameAr: "هندوراس", nameEn: "Honduras", flag: "https://flagcdn.com/w40/hn.png" },
  { nameAr: "السلفادور", nameEn: "El Salvador", flag: "https://flagcdn.com/w40/sv.png" },
  { nameAr: "نيكاراغوا", nameEn: "Nicaragua", flag: "https://flagcdn.com/w40/ni.png" },
  { nameAr: "كوستاريكا", nameEn: "Costa Rica", flag: "https://flagcdn.com/w40/cr.png" },
  { nameAr: "بنما", nameEn: "Panama", flag: "https://flagcdn.com/w40/pa.png" },
  { nameAr: "كوبا", nameEn: "Cuba", flag: "https://flagcdn.com/w40/cu.png" },
  { nameAr: "جامايكا", nameEn: "Jamaica", flag: "https://flagcdn.com/w40/jm.png" },
  { nameAr: "هايتي", nameEn: "Haiti", flag: "https://flagcdn.com/w40/ht.png" },
  { nameAr: "جمهورية الدومينيكان", nameEn: "Dominican Republic", flag: "https://flagcdn.com/w40/do.png" },
  { nameAr: "بورتوريكو", nameEn: "Puerto Rico", flag: "https://flagcdn.com/w40/pr.png" },
  { nameAr: "البهاما", nameEn: "Bahamas", flag: "https://flagcdn.com/w40/bs.png" },
  { nameAr: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago", flag: "https://flagcdn.com/w40/tt.png" },
  { nameAr: "باربادوس", nameEn: "Barbados", flag: "https://flagcdn.com/w40/bb.png" },
  { nameAr: "سانت لوسيا", nameEn: "Saint Lucia", flag: "https://flagcdn.com/w40/lc.png" },
  { nameAr: "غرينادا", nameEn: "Grenada", flag: "https://flagcdn.com/w40/gd.png" },
  { nameAr: "سانت فينسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w40/vc.png" },
  { nameAr: "أنتيغوا وباربودا", nameEn: "Antigua and Barbuda", flag: "https://flagcdn.com/w40/ag.png" },
  { nameAr: "دومينيكا", nameEn: "Dominica", flag: "https://flagcdn.com/w40/dm.png" },
  { nameAr: "سانت كيتس ونيفيس", nameEn: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w40/kn.png" },
  { nameAr: "كولومبيا", nameEn: "Colombia", flag: "https://flagcdn.com/w40/co.png" },
  { nameAr: "فنزويلا", nameEn: "Venezuela", flag: "https://flagcdn.com/w40/ve.png" },
  { nameAr: "غيانا", nameEn: "Guyana", flag: "https://flagcdn.com/w40/gy.png" },
  { nameAr: "سورينام", nameEn: "Suriname", flag: "https://flagcdn.com/w40/sr.png" },
  { nameAr: "غويانا الفرنسية", nameEn: "French Guiana", flag: "https://flagcdn.com/w40/gf.png" },
  { nameAr: "الإكوادور", nameEn: "Ecuador", flag: "https://flagcdn.com/w40/ec.png" },
  { nameAr: "بيرو", nameEn: "Peru", flag: "https://flagcdn.com/w40/pe.png" },
  { nameAr: "بوليفيا", nameEn: "Bolivia", flag: "https://flagcdn.com/w40/bo.png" },
  { nameAr: "البرازيل", nameEn: "Brazil", flag: "https://flagcdn.com/w40/br.png" },
  { nameAr: "باراغواي", nameEn: "Paraguay", flag: "https://flagcdn.com/w40/py.png" },
  { nameAr: "الأوروغواي", nameEn: "Uruguay", flag: "https://flagcdn.com/w40/uy.png" },
  { nameAr: "الأرجنتين", nameEn: "Argentina", flag: "https://flagcdn.com/w40/ar.png" },
  { nameAr: "تشيلي", nameEn: "Chile", flag: "https://flagcdn.com/w40/cl.png" },

  // Oceania
  { nameAr: "أستراليا", nameEn: "Australia", flag: "https://flagcdn.com/w40/au.png" },
  { nameAr: "نيوزيلندا", nameEn: "New Zealand", flag: "https://flagcdn.com/w40/nz.png" },
  { nameAr: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea", flag: "https://flagcdn.com/w40/pg.png" },
  { nameAr: "فيجي", nameEn: "Fiji", flag: "https://flagcdn.com/w40/fj.png" },
  { nameAr: "جزر سليمان", nameEn: "Solomon Islands", flag: "https://flagcdn.com/w40/sb.png" },
  { nameAr: "فانواتو", nameEn: "Vanuatu", flag: "https://flagcdn.com/w40/vu.png" },
  { nameAr: "كاليدونيا الجديدة", nameEn: "New Caledonia", flag: "https://flagcdn.com/w40/nc.png" },
  { nameAr: "بولينزيا الفرنسية", nameEn: "French Polynesia", flag: "https://flagcdn.com/w40/pf.png" },
  { nameAr: "ساموا", nameEn: "Samoa", flag: "https://flagcdn.com/w40/ws.png" },
  { nameAr: "تونغا", nameEn: "Tonga", flag: "https://flagcdn.com/w40/to.png" },
  { nameAr: "كيريباتي", nameEn: "Kiribati", flag: "https://flagcdn.com/w40/ki.png" },
  { nameAr: "ولايات ميكرونيسيا المتحدة", nameEn: "Micronesia", flag: "https://flagcdn.com/w40/fm.png" },
  { nameAr: "جزر مارشال", nameEn: "Marshall Islands", flag: "https://flagcdn.com/w40/mh.png" },
  { nameAr: "بالاو", nameEn: "Palau", flag: "https://flagcdn.com/w40/pw.png" },
  { nameAr: "ناورو", nameEn: "Nauru", flag: "https://flagcdn.com/w40/nr.png" },
  { nameAr: "توفالو", nameEn: "Tuvalu", flag: "https://flagcdn.com/w40/tv.png" }
];
